### ISSUE TITLE
Program crash on Vorze speed multiplier

### ISSUE THREAD

**Issue by barraged1** [FredTungsten/ScriptPlayer#102]
Encountered a strange bug with beta version(possibly the current release too) where increasing the Speed Multiplier when using a Vorze causes the program to crash after about hitting 2-3 movement commands.

The was on the most recent buttplug update (initface) and Scriptplayer 1.0.5.209

**Comment by FredTungsten** [comment]
Unfortunately I don't have a Vorze to reproduce this. Can you post the stack-trace? (Evenlog or `%APPDATA%\\ScriptPlayer\\Crash.log`

**Comment by barraged1** [comment]
[Crash.log](https://github.com/FredTungsten/ScriptPlayer/files/3390246/Crash.log)

Here you go.

**Comment by FredTungsten** [comment]
Hmm ... unfortunately that didn't contain any helpful information - at least I can't find anything related to Vorze commands or Intiface.
