### ISSUE TITLE
Localization and timestamps from Whirligig 4.75.72

### ISSUE THREAD

**Issue by TibbeAtGitHub** [FredTungsten/ScriptPlayer#104]
Whirligig was recently updated to 4.7572. The code related to the time server seems to have been updated and when using non-US English localization in Windows, all time stamps are stacked in the beginning of the heat map. It looks like a solid blue area. The synchronization is 
completely broken.

The Whirligig devs fixed some localization issues already, but according to them the remainder of the fix is on the ScriptPlayer side. This is the response I've got: 

> I just tested and can confirm that the connection from Whirligig to ScriptPlayer/Whirlisync is still broken. This time it's due to a problem on the script players side though. Those applications will need updating for it to work with the latest Whirligig version. In the mean time please use v.4.72 like you are doing right now.

I don't know exactly what has changed in Whirligig, but it is related to localization.

I'm located in Europe.
Non-english Windows 10 Home (build 1903), fully patched.
Decimal comma is used (not decimal point as in the US).
I have 24-hour time setup (i.e. 16:00 instead of 4pm) and is in the UTC+1 time zone (currently CEST instead of CET due to daylight saving time).
Dates are in YYYY-MM-DD format.

**Comment by FredTungsten** [comment]
Should be fixed in the commit I just pushed, unfortunately it seems to have another error: It seems like Whirligig always sends the duration of the previous video, not the one currently playing.
