### ISSUE TITLE
Requests: Enhanced Settings

### ISSUE THREAD

**Issue by qwksilver** [FredTungsten/ScriptPlayer#105]
So there are a few things I'd love to see, no idea how complicated any of these are.
1:  Buttplug, add an option to launch a specific file/location(intiface) when scriptplayer is loaded.
2:  "Auto Connect to Buttplug" delay before connect, timeouts, and retry options too.
3:  Buttplug:  "auto show device manager" & "auto scan for devices" after connecting to buttplug
4:  General or Player: "Default Player Mode"
5:  Paths, add a way to specific main+sub folders (ie.  ...\LaunchScripts\*)
6:  A path for fallback scripts to be randomly pulled from, instead of just one file.

**Comment by FredTungsten** [comment]
1. Shouldn't be a problem
2. Probably
3. Sure, why not
4. Have you tried Settings / Remember / Playbackmode ? Does something very similar
5. No Idea what you mean - could you describe that one in more detail?
6. Probably not, we'll see.

**Comment by gagax1234** [comment]
> 5. No Idea what you mean - could you describe that one in more detail?

I'm obviously not him but I think what he means having the ability to set paths to be recursively searched.
If that's not it I think that be nice :sweat_smile:

**Comment by qwksilver** [comment]
5. in the paths part, i have to manually enter each sub-directory I want it to search.  so if i have a tree:
C:\Dropbox\Scripts\
C:\Dropbox\Scripts\Good Files
C:\Dropbox\Scripts\Unmatched
C:\Dropbox\Scripts\Best Models Ever
C:\Dropbox\Scripts\Collection
C:\Dropbox\Scripts\Collection\Alex Grimes Scripts
C:\Dropbox\Scripts\Collection\Dana Allgood Scripts

I think it would be much easier to put one entry like
C:\Dropbox\Scripts\*  and have it search both the scripts directory and all the subs and subs-subs and so on below the main search point

**Comment by FredTungsten** [comment]
Oh! Yeah, no problem 😄

**Comment by FredTungsten** [comment]
5 should work now

**Comment by qwksilver** [comment]
just downloaded the artifact.  the * setting works nice, on the feedback screen it's finding all the subs and mains, and doesn't seem to see a difference between these two locations:
E:\Dropbox\$Deck\launchscripts*
E:\Dropbox\$Deck\launchscripts\*
So either one reports scripts loaded(note I never used both together, just one or the other)
note the problem below occurs with either config, and with "remember-playback mode" checked

Issue: With any file it loads, the heatmap isn't there, nor are the script moves.  Red lines and the space for the heatmap are present, but both are empty, 

If I then change from zoomplayer to local it works locally, if I change back to zoomplayer it works from there on.  If I close, and restart, with remember playback mode on, it doesn't work again.

if remember playback mode unchecked, and setup zoomplayer manually after opening, then it works fine.

this occurred with intiface off, so I tried it with intiface on, and same issue, didn't ever attach device.

**Comment by FredTungsten** [comment]
> [...] and doesn't seem to see a difference between these two locations:
> E:\Dropbox$Deck\launchscripts*
> E:\Dropbox$Deck\launchscripts*

I don't see a difference either to be honest.
The other thing I can take a look at - I've never gotten any feedback for that setting so I wouldn't be surprised to find a few bugs.

**Comment by FredTungsten** [comment]
1: Done
2: Partially done (no delay, timeouts or retries)
4: Might be fixed now

**Comment by FredTungsten** [comment]
2: Done

**Comment by qwksilver** [comment]
ok the default player frozen script problem has gone away with .219
which basically means all of this issue has been managed except #6 which got a probably not in the first place.  I also say Wow, this has made the whole process very automatic within my current media center.  I thank you.

**Comment by FredTungsten** [comment]
Oh well, we've already come this far - might as well see it trough 😉 

6: Done

**Comment by qwksilver** [comment]
First #6 working!  love .220

Second, this might be asked and answered elsewhere.
a selected script shorter than the video will quit well before they video ends, is it possible to loop them, or do they have to be build really long to accommodate that situation.

example.
![sample](https://user-images.githubusercontent.com/20508309/64311043-984d4b80-cf70-11e9-881f-8e965a2aa4f2.jpg)

**Comment by FredTungsten** [comment]
Added two new settings:
- Loop the fallback script for the entire duration of the video
- Remove any gaps > 10 seconds (works in combination with the other option too)

**Comment by qwksilver** [comment]
this I think slams the door on #105, .222 works great, love the loop+gap killer,

**Comment by FredTungsten** [comment]
Glad you like it 😄 
I'm closing this issue since everything is done now, but feel free to create new ones for further feature requests.
