### ISSUE TITLE
Feature Request: Increase Script Delay to 2s range

### ISSUE THREAD

**Issue by MaryAtlas** [FredTungsten/ScriptPlayer#109]
I am facing a delay of around 1 to 2 seconds when syncing scripts with Samsung VR via Presentation Mode. It would be very good if you could increase the length of the script delay to around +- 2 seconds. Thanks

**Comment by MaryAtlas** [comment]
I am facing a delay of around 1 to 2 seconds when syncing videos on Samsung VR via Presentation Mode. It would be very good if you could increase the length of the script delay to around a 2 seconds range.

**Comment by FredTungsten** [comment]
Done in 851697d986f1e2ea2c13b601d735d2966801696b
