### ISSUE TITLE
OSD Messages for external players

### ISSUE THREAD

**Issue by qwksilver** [FredTungsten/ScriptPlayer#110]
This is related to #106 (option b of this)

Option A:
I looked into a few things, one fairly accessible thing might be function 1200 to send simple OSD messages to zoomplayer.  I'm not sure about sending OSD to other players.
Zoom player documentation here:  http://forum.inmatrix.com/index.php?showtopic=3335

Option B:
determine what monitor the external video player is on, and send an OSD message to that monitor "on top of all/highest strata"  say centered and 3% down from top.  This would work reguardless of player in use.  This would also have the added advantage of starting the overlay functions that would make issue #106 more feasible.

The messages being the ones that show up on script player itself. Like "loading...", or "script delay 125", or "no script found, loading backup...." and so on.  Essentially anything send to OSD there.

Possible Change "Debug" to Player Options, and add it there. With sections for Default Player Only, and Remote Players.

**Comment by FredTungsten** [comment]
*Might* happen

**Comment by qwksilver** [comment]
.225 does send message nice and clean to zoom player, those messages look just like zoomplayers normal messages like play pause etc.

However, it seems like if there are multiple message to send.  
Scriptplayer puts them on progressive lines.
zoomplayer stacks them on top of one another with the latest on top.

depending on how many there are and what lengths this looks kinda funky
is there a clear osd existing that can be sent before the new osd message is placed?

assumption: zoomplayer itself won't "newline" each message and then retire them and slide up similar to what SP does.  I have checked ZP and it doesn't have a # of lines options in the osd setup.

**Comment by FredTungsten** [comment]
Right now I'm just pushing messages as I would with the built-in OSD. Unfortunately Zoomplayer doesn't seem to have a way to clear existing messages so they just show up on top of each other.

**Comment by qwksilver** [comment]
Related Issue:
```
"Matching Script already loaded"
"Matching Script already loaded"
"Matching Script already loaded"
"Matching Script already loaded"
```

shows up on scriptplayer, and the osd never leaves zoomplayer.
every second it flicks the top one off and comes up with another one on bottom.

also the "overlapping" problem is looking like a one time thing.

**Comment by qwksilver** [comment]
More info:  this only happens when using the search scripts directory, for any video with the matching file, this doesn't occur.  This also overloads the OSD list on ZoomPlayer and eventually causes an error message there (Index list out of bounds) and requires me to kill ZP and restart.  I do not have to restart ScriptPlayer.  During the few minutes before the error, script files act erraticly, and don't play in sync to video.

**Comment by FredTungsten** [comment]
I am so far unable to reproduce this issue. What exactly are you doing to make this happen?

**Comment by qwksilver** [comment]
ok so i have a "look here" setup in paths
e:\Dropbox\$Deck\launchscripts*

I also have a directory with a bunch of paired files, e:\Dropbox\$Deck\launchscripts\paired

if i use a paired file, it works fine
if i use a file with no match, it works fine

if i use a file with a match, but the main media file is in another location, not (e:\Dropbox\$Deck\launchscripts or subs) it causes this repeating message issue.

this is using the zoom player osd, not sure if it's an issue without external player.

**Comment by FredTungsten** [comment]
Still no luck with reproducing this 😒 
I've added a couple of filters that *might* solve the problem.
If it still doesn't work - I've also added a new setting "Notifications/Use external OSD if available" so you can at least turn it off if it still doesn't work (default is off so you would have to enable it first).

**Comment by qwksilver** [comment]
Ok, OSD working, and problem is gone, quick test, I'll let you know if it shows up durring a longer test.  I suppose this is closed unless another issue crops up, but OSD is looking and working nice.
