### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by qwksilver** [FredTungsten/ScriptPlayer#111]
1:  I can't get scriptplayer to accept ANY keyboard input from Girder 5 when it isn't top focus.  My automation software can send a command directly to a specific window, but it can't send a command into scriptplayer.  I have to force it to top focus, and then send a keyboard focus based command.  This does work with a bunch of other software, so I know it's not the automation side.

2:  Keyboard learning shows some weird things like NUMBERPAD+ shows as ADD, and ] shows as OEM6, this seems odd, and may be connected to issue one, right now I use lowercase "t" & "y" for decrease & increase script delay.  I was going to use + & - on the numberpad.

**Comment by FredTungsten** [comment]
1) Probably still uses the old WndProc WM_SENDKEY messages that Windows Forms used. WPF has an entirely different input model, but making some kind of makeshift adapter might be possible.

2) Same issue - Winforms and WPF input models are very different.

**Comment by qwksilver** [comment]
so i read this article and have a better understanding of what you mean.
https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/windows-forms-and-wpf-interoperability-input-architecture

I'm looking for a girder5 keyboard module that uses WPF, but at the moment I have a change focus, push key, work around functioning, that is allowing me to do what I wish.  Honestly I just thought it emulated the keyboard itself, and sent the key to the program as though the program were the focus.  but alas that which is under the seen layer is often baffling to me.

**Comment by qwksilver** [comment]
no change, it's almost like if it isn't in focus it doesn't listen.

**Comment by FredTungsten** [comment]
That's unfortunate :(
If it isn't using WM_SENDKEY, I have no idea what else it could be.

**Comment by qwksilver** [comment]
so....i brain farted, so disregard that no change message, i tested before i realized i haven't downloaded the point release.

**Comment by qwksilver** [comment]
.225 has immediate crash
crash is before and after reboot, before and after reinstall (.225).
First install zoom player was running, but scriptplayer was not.
second install, zoom and script player were not running.
have now tried both release.225 and debug.225

[Crash.log](https://github.com/FredTungsten/ScriptPlayer/files/3633955/Crash.log)

renaming settings.xml.old allows program run.
  <AutoStartButtplug>false</AutoStartButtplug>
  <AutoConnectToButtplug>false</AutoConnectToButtplug>
are required, if either line is true, immediate fail.

hope that is enough to find.

**Comment by qwksilver** [comment]
I moved the crash resolution to a different issue, this is feedback on just this.
once I got .225 running there it is accepting command directly inserted regardless of focus.
this is likely closed unless it reappears.

**Comment by FredTungsten** [comment]
👍
