### ISSUE TITLE
Crash .225

### ISSUE THREAD

**Issue by qwksilver** [FredTungsten/ScriptPlayer#112]
> .225 has immediate crash

crash is before and after reboot, before and after reinstall (.225).
First install zoom player was running, but scriptplayer was not.
second install, zoom and script player were not running.
have now tried both release.225 and debug.225

[Crash.log](https://github.com/FredTungsten/ScriptPlayer/files/3633955/Crash.log)

renaming settings.xml.old allows program run.
resuming settings.xml and trying to block just a few settings
```
<AutoStartButtplug>false</AutoStartButtplug>
<AutoConnectToButtplug>false</AutoConnectToButtplug>
```
are required, if either line is true, immediate fail.

checking the boxes and resaving, exit, reload, crash

hope that is enough to find/fix.

**Comment by FredTungsten** [comment]
Should be fixed now

**Comment by qwksilver** [comment]
crash removed in my environment as well.
