### ISSUE TITLE
Scriptplayer not loading script when using Samsung gear VR

### ISSUE THREAD

**Issue by 4kingwinner** [FredTungsten/ScriptPlayer#113]
Hi, Newbie here. First and foremost, what a great site. I'm new to all this but keen to learn and get stuck in so I can add value ;) 

I am having trouble using Scriptplayer with Samsung VR, any advice on how I might get this fixed would be greatly appreciated. 

I have Scriptplayer installed on WINDOWS 10 through MAC OSX BOOTCAMP connected to Fleshlight Launch using Buttplug.

I have set the 'Paths' for my funscripts and I am Using UDP port 5000.

Everything works perfectly until I try and use Samsung VR Video player, it connects but it will not load the funscript once I select the video file on on Samsung vr through my Gear VR/Samsung Galaxy S10.   

I have changed settings to presentation mode but still nothing

Please help?

**Comment by raser1** [comment]
Hi 4kingwinner, maybe you have the new version of Samsung VR which doesn't work with ScriptPlayer anymore. You will need to remove it and download an older version. Please check: http://realtouchscripts.com/viewtopic.php?f=55&t=8535&p=22655#p22669

**Comment by 4kingwinner** [comment]
Thanks so much for the swift reply raser1, you're a legend!!! I'll give your suggestion a go and report back.

**Comment by FredTungsten** [comment]
Thanks for taking care of this 👍

**Comment by 4kingwinner** [comment]
raser1 you are an absolute star...Thanks so much for this. It now work...now time to get my head round some script making and coding. Honored to be a part of such a cool movement. Keep up the great work.

**Comment by raser1** [comment]
No problem. :) 

Make sure to check out JoyFunScripter if you haven't done so yet: http://realtouchscripts.com/viewtopic.php?t=6565
