### ISSUE TITLE
Whirligig not working

### ISSUE THREAD

**Issue by UltraJohn** [FredTungsten/ScriptPlayer#117]
Hello. I have followed the guide to connect ScriptPlayer to Whirligig by setting up the timecode server. When I load a video in whirligig it is recognized by ScriptPlayer and connected to my launch. However when i play the video, the timeline shown in ScriptPlayer runs at what looks like 1000x speed, and then instantly says the script ran out of events. As such, I am unable to actually get it to work properly. I am using an Oculus rift. Scripts work just fine in local mode, just not through whirligig with VR.

**Comment by FredTungsten** [comment]
Are you using the release version or the latest build of ScriptPlayer?
([How to download the latest beta build](https://github.com/FredTungsten/ScriptPlayer/wiki/Downloading-Beta-Builds))

For whatever reason, the dev of Whirligig dev decided to change the comma separator some time ago and I fixed that issue back then.

**Comment by FredTungsten** [comment]
Potential duplicate of #104

**Comment by UltraJohn** [comment]
I'm using the version downloaded from oculus store, I would assume that's the release version. Will it work with the beta?

**Comment by FredTungsten** [comment]
No I  mean the ScriptPlayer version, not Whirligig version

**Comment by UltraJohn** [comment]
I have 1.0.5

**Comment by FredTungsten** [comment]
Try the current ScriptPlayer beta (link in first comment), I already fixed that issue - there might be a new one but unfortunately I never heard back on that.

**Comment by UltraJohn** [comment]
Thank you, I'll let you know if the beta has issues as well.
