### ISSUE TITLE
Increase Launch movement range from the limits 0-99

### ISSUE THREAD

**Issue by martzink** [FredTungsten/ScriptPlayer#118]
Hello, I like using your scriptplayer software together with the Launch and funscripts.

I would like to be able to increase the movement range from the maximum 0-99 to get longer movements.

I have experimented a bit with the Launch and I find that there is a bit of extra movement  possible before hitting the mechanical stops, seems to be about two centimeters unused, one centimeter movement each way from where the launch stops until it bumps into the mechanical stops.

I read about the range limits being set to these values between 5-95 in the buttplug documents to prevent bumping against the mechanical stops, however I think it should be possible to increase the range a little bit before it starts bumping.

I don't remember which program it was, but I was able to increase the range, the maximum I could use was around (-4 to 105)  . Sometimes it would bump into the stops a little bit at very fast movements, but the extra movement range was very cool and I miss that a bit with scriptplayer. 

Thanks for making this software, it's great!

**Comment by FredTungsten** [comment]
Hi, glad you like it 😃 

The 0-99 are the maximum values the launch Bluetooth protocol will accept (and even at those values the slide can hit the mechanical stops so I usually keep it at 5-95 too). If you remember what software it was I can take a look.

**Comment by FredTungsten** [comment]
B.t.w: If a script doesn't use the full range it gets extended automatically to the range set in ScriptPlayer and smaller movements can be extended to the max (or just a little) with the "Range Extender" setting.

**Comment by martzink** [comment]
Hello, thank you for the reply.

I see, so that is how it works.
Hmm I still can't remember what software it was. 
Perhaps the movement range is the same as I remember it before. Must be so since you say it can't go over 0-99.

Cool, now I know a bit more about it. Have a nice day 🙂
