### ISSUE TITLE
Ability to invert Position to Vibration mapping for vibrators

### ISSUE THREAD

**Issue by dastardlii** [FredTungsten/ScriptPlayer#119]
I'd like to request the ability to invert the device output for vibrators.  So instead of position 100 being a max vibration and 0 being off, 100 would be off and 0 would be maximum vibration.

It would be extra nice if this was something that could be toggled easily.  Maybe from the right-hand settings menu?

**Comment by FredTungsten** [comment]
I haven't tried it yet (lack of vibrators and time), but the "Invert Positions" options (also available in the right-hand menu) should also work for vibrators. If not: should be an easy fix - just tell me after you tried it and I'll deep-dive into that section of the code 😄

**Comment by FredTungsten** [comment]
Update: it probably doesn't work in the "Convert position to speed" mode.

**Comment by dastardlii** [comment]
Tested it and confirmed what you said above, that invert doesn't work with pos2speed mode.  The device is a Lovense Hush controlled through Initface BTW.  

Would it be possible to split that mode into two different ones?  Po2Speed and Pos2SpeedInverse?

What I'd really like to do is have a launch and a vibe connected at the same time.  The "use speed" mode actually works really well this way, but it would be nice to be able to control whether the vibe is full power when the launch is fully in, or full power when the launch is fully out.

It may not be possible to control 2 devices like that and have them work in opposite ways, but the new modes made me think it might be possible.

**Comment by FredTungsten** [comment]
Two modes might be the best solution for this.

Ideally each device would have it's own complete set of settings (range, speed, invert, delay, etc.) but atm this would be way too much work.

**Comment by FredTungsten** [comment]
Added in 0863b1de3fa216655789bb3bfc2b683cc10de24b
