### ISSUE TITLE
Auto-Loop short videos

### ISSUE THREAD

**Issue by FredTungsten** [FredTungsten/ScriptPlayer#120]
From RTS http://www.realtouchscripts.com/viewtopic.php?f=59&t=9190

The program typically skips videos that are shorter than the length given in the random section option. So if it is set to 60 sec random sections, and a short video of 30 secs comes along, it will just skip it. I have spent some time editing some of the smaller videos I had, which were basically just looped gifs. Would it be possible to have ScriptPlayer just auto-loop videos when they are shorter than the random section interval? So that 10 second gif would just be looped for 60 sec and then ScriptPlayer would move on to the next video?

**Comment by MarkusWo** [comment]
I was the one who requested this. To be honest, I just don't like when ScriptPlayer straight up skips some of my videos. If looping the videos that are shorter than the random section setting is not that easy, It would also be enough if ScriptPlayer just played those shorter videos exactly once. Even if they are just 15 seconds. ThankS

**Comment by FredTungsten** [comment]
That's certainly doable

**Comment by FredTungsten** [comment]
Short videos should now play without issues
