### ISSUE TITLE
Add more keyboard mappings

### ISSUE THREAD

**Issue by FredTungsten** [FredTungsten/ScriptPlayer#122]
From RTS:

For VR the keyboard mappings are indispensable so more options there would be fantastic, namely a way to change the range on the fly by extending/lowering it or by activating F, B, etc.

**Comment by ggregor-44** [comment]
I miss especially the Filter Range mapping. It is really useful for adjusting the intensiveness on the fly.

**Comment by FredTungsten** [comment]
Done
