### ISSUE TITLE
Video syncronisation with VRTV App for Android

### ISSUE THREAD

**Issue by MaulWuii** [FredTungsten/ScriptPlayer#123]
VRTV is a VR Video Player for Android. It's availabe for free and there is also a payed version. This player has a syncronisation feature that keeps a movie in sync between two devices, if VRTV is running on both devices. If there would be the possibility to sync VRTV with ScriptPlayer instead of an other device with VRTV could that be the solution for all smartphone users.

**Comment by FredTungsten** [comment]
Do you have a link to a public API for that?

**Comment by MaulWuii** [comment]
Sorry, i dont get any answer from the creators of the app. So no, there is no public API. You can close this issue.
