### ISSUE TITLE
autohome on pause for whirligig

### ISSUE THREAD

**Issue by scythen60** [FredTungsten/ScriptPlayer#125]
autohome on pause works well for local playback, but does not appear to be working for whirligig, and possibly other external players.

**Comment by FredTungsten** [comment]
Might be broken again ... 😒

**Comment by gagax1234** [comment]
> Might be broken again ... 😒

Yeah... I think I've caused a race condition.
The command queue gets cleared before the Homing Command gets executed.
I'm going to have another look.

**Comment by gagax1234** [comment]
I have another fix 😳 ff64411ceeaba6bb0b49fbb75c676361231bfb5a
I removed the two calls to StopDevices from the Pause method in MainViewModel.cs which isn't called when using another Video Player and put one call to StopDevices into the TimeSourceIsPlayingChanged when playing == false right before the AutoHomeDevices() this should ensure the command queue gets cleared before the homing command gets inserted and that StopDevices is called whenever the player gets paused.
So far I have only tested this with a mock device and a bunch of Debug.WriteLine's.
So I'm going to wait on making a pull request till I tested this with the real thing.😅

**Comment by scythen60** [comment]
#131 seems to be working great on whirligig and vlc. thanks @gagax1234

**Comment by FredTungsten** [comment]
Can confirm it also works with local playback, thx gagax 👍
