### ISSUE TITLE
 Request to add a new Kiiroo Onyx + (plus)

### ISSUE THREAD

**Issue by WrobelK** [FredTungsten/ScriptPlayer#129]
Hello, just like the subject - please add support for the new **Kiiroo Onyx +**

**Comment by WrobelK** [comment]
[url=https://ibb.co/99XryYb][img]https://i.ibb.co/272kcKv/onyx.png[/img][/url]

**Comment by FredTungsten** [comment]
That would be qDot's kind of thing (buttplug/intiface):
https://github.com/buttplugio/buttplug-csharp/issues
