### ISSUE TITLE
way to fast speed

### ISSUE THREAD

**Issue by Jonasma703** [FredTungsten/ScriptPlayer#133]
when i connect to whirligig the speed goes super fast, and the the video progress bar can show times up to several hours for mere minutes of video time in the whirligig player

**Comment by FredTungsten** [comment]
Are you using the latest version of ScriptPlayer?

https://github.com/FredTungsten/ScriptPlayer/issues/104  
https://github.com/FredTungsten/ScriptPlayer/issues/117

**Comment by Jonasma703** [comment]
I had to pick early access latest beta on the whirligig program and it fixed the problem completely.
