### ISSUE TITLE
webm files no longer play

### ISSUE THREAD

**Issue by Ligerx** [FredTungsten/ScriptPlayer#135]
v1.1.0
Windows 10
I believe webm files were working in the previous version, but they aren't any more.

**Comment by FredTungsten** [comment]
That's not much to go on.
Here are a couple of things you can try:
Does it actually work with the previous version?
Does it work in Windows Media Player?
Does it when when you install one of the recommended codec packs?
(https://github.com/FredTungsten/ScriptPlayer/wiki/Troubleshooting)

**Comment by Ligerx** [comment]
It works in the windows built in Movies & TV app, Windows Media Player, and MPC.

I do definitely remember it working in previously for me. But right now, when I tried to install the last couple versions of ScriptPlayer, it doesn't work.

I already had K-Lite Codec Pack v14.3.6 installed.

**Comment by Ligerx** [comment]
Aha, for some reason updating K-Lite to the latest v15.4.4 seems to fix the problem. Not sure why I was running into this issue in the first place since it was working before.

Thanks for the help @FredTungsten
