### ISSUE TITLE
Make random section really random

### ISSUE THREAD

**Issue by MarkusWo** [FredTungsten/ScriptPlayer#137]
I am using the Random Section option (target duration 180s) and I have noticed that for many scripts, the section that is chosen is (almost) always the same. The attached file shows the heatmap of a video that I have now tried multiple times and always receive the exact same section at 13:17, as shown in the screenshot. Can you look if your random section algorithm has any biases or whatever, which make it act non-randomly in some cases?

From my own observations I would presume it has to do with how this video has long gaps, like many anime videos. I think the random section algorithm always ignores the assorted shorter bits to the beginning of the script and thus ends up selecting the longest uninterrupted piece of script. I have also activated the option "Fill gaps with movement" with fill before and after last action. So, I don't mind the gaps between the shorter pieces of action. In fact, I would expect the random section algorithm to occasionally pick a bit that is only gap in the middle or the end of the script. I wouldn't mind at all if that happens, because sometimes there's intersting things in the gaps. I use a very slow speed to fill the gaps so those would be very welcome short breaks.

So, can you check if the random section algorithm can be made "completely" random without biasing towards the largest uninterrupted section in a script (if that is what is happening here)? Also, can you make it so that even gaps are randomly selected at times, as well as those parts which have short sections of action and gaps intertwined (see first third of attached heat map)? Maybe make this the default behavior if you have random section + Fill gaps with movement selected or add an option for those people that never want to see gaps.

Thank You!

![heatmap](https://user-images.githubusercontent.com/17179276/82211819-c3ff3e80-9911-11ea-88d5-d731584b8fcc.jpg)

**Comment by MarkusWo** [comment]
Here the script, where I always get the same section "randomly". Notice, this is a funscript file, I just had to rename it to txt because of github restrictions. Just rename it back to .funscript.
[eroge-sex-game-make-sexy-games-2.txt](https://github.com/FredTungsten/ScriptPlayer/files/4644073/eroge-sex-game-make-sexy-games-2.txt)

**Comment by FredTungsten** [comment]
It's random within sections that contain (scripted) content. In this script there isn't a single section of at least 180s of continuos script so the longest one is selected as a fallback. 

I've added an additional option to include filled gaps in the selection of random sections.
https://github.com/FredTungsten/ScriptPlayer/wiki/Downloading-Beta-Builds

**Comment by MarkusWo** [comment]
It works like a charm. Thank You!
