### ISSUE TITLE
2 Minor Requests (Script Delay Related)

### ISSUE THREAD

**Issue by qwksilver** [FredTungsten/ScriptPlayer#139]
1. Script Delay, when using keyboard to add/subtract delay won't progress past 500 I think, if you are above 500 you can reduce the delay but not increase it back.
2. The Slide out Panel with Settings and Delay, can it remember if it's pinned from session to session, or have a default of pined/not pined/last setting.  This might also be useful in playlist.

**Comment by FredTungsten** [comment]
1 - fixed (2500 ms)  
2 - should already work like that

**Comment by qwksilver** [comment]
2 - mine doesn't every time i leave and reopen the player the panel is closed.
i'll check this again tomorrow too, and see if it's related to being in external video mode

**Comment by FredTungsten** [comment]
You probably don't have the "Remember Window Position" option active

**Comment by qwksilver** [comment]
These have been resolved
