### ISSUE TITLE
Feature Request:  Allow Mouse Wheel to be used in Input Mappings

### ISSUE THREAD

**Issue by eleven12s** [FredTungsten/ScriptPlayer#144]
It would be 'nice' to be able to assign the mouse wheel to Input Mappings.

**Comment by FredTungsten** [comment]
Done - all mouse buttons can now be assigned to an input mapping (left, right, middle, X1, X2, wheel up, wheel down).
If they are not used the default commands will still work (left click = play/pause and toggle fullscreen, right click = log marker).
Double-clicks can't be mapped yet.
