### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by ftreesmilo** [FredTungsten/ScriptPlayer#154]
I see a few features here that have been requested that a project of mine already supports.
Video player, overlays, programmatic control, script driven interaction, session storage, etc: (https://milovana.com/forum/viewtopic.php?p=284684#p284684)

I am missing any sort of estim support or capabilities.
Would you be interested in contributing a webusb implementation of your estim support? I have no experience in this area, and I'm looking to make this site more attractive to creators.

**Comment by FredTungsten** [comment]
To be honest I have no clue about audio or e-stim but I have a pending PR from someone who does. Never heard of webusb before but I'll revisit that idea once I have a bit more knowledge on either of those topics

**Comment by ddumont** [comment]
The e-stim stuff seems to be very similar to the other scriptable stuff like the Fleshlight.  Whether it's the fleshlight or estim stuff, I'd be happy to work with you to get that functionality working via my app.

**Comment by ftreesmilo** [comment]
The estim stuff, I believe is very much like your fleshlight support.  I'd be happy to work with you on getting support for any and all of it when you get the time. Let me know!

**Comment by qwksilver** [comment]
#155 maybe related to this implementation, or may be exacerbated by it.

**Comment by qdot** [comment]
@ftreesmilo I'd be happy to talk to you more about WebUSB and estim support in Buttplug. I'm currently moving Buttplug-js to a rust based WASM blob which will have WebBluetooth, WebUSB, and WebSerial support. This will live alongside native support for estim, which will be coming back up soon (and will mean @FredTungsten has less integration to do in ScriptPlayer :3 )

**Comment by github-userx** [comment]
@FredTungsten if I remember correctly webusb is also being used when web browsers use/access stuff like the Yuri key/2FA USB keys:

https://www.wired.com/story/chrome-yubikey-phishing-webusb/

Just for some interesting background info :)

thanks for all your great work!

**Comment by qdot** [comment]
> 
> 
> @FredTungsten if I remember correctly webusb is also being used when web browsers use/access stuff like the Yuri key/2FA USB keys:
> 
> https://www.wired.com/story/chrome-yubikey-phishing-webusb/
> 
> Just for some interesting background info :)
> 
> thanks for all your great work!

That was a story from 2 years ago, citing a problem with the VID/PID and device class blacklisting. No clue what it has to do with this thread?
