### ISSUE TITLE
 Bug Crash: estim audio vs funstim (with Device screen improvement requests)

### ISSUE THREAD

**Issue by qwksilver** [FredTungsten/ScriptPlayer#156]
if one is open, and you open the other, the whole player vanished/crashed. 
repeatable, funstim on,. then audiostim=crash before dialog
repeatable, audiostim on..then funstim=crash before dialog
test can I disable device and then load other, and switch back and forth.  NOPE still crashes if other device exists.

I can't seem to kill a "device" once started so to change from one to the other you have to exit/restart

a. so a check before loading with a prompt to close the conflicting device
b. or allowing them to run concurently forcing the older to disable when the newer is on, and forging the 

1. i think this is elsewhere, but a trashcan or something on the farside of devices from X and check would be nice to just stop that unit
2. an "always on top" for the device screen would be nice too.
3. and a keybinding to hide/show that screen of course :>

**Comment by FredTungsten** [comment]
Oh, I just fixed this while testing - the funstim implementation had some copy&pasted code from my e-stim implementation that caused a double registration.

Removing devices is something I should definitely add. I never planned on implementing so many directly in scriptplayer since that is what buttplug/intiface is actually for.

**Comment by qwksilver** [comment]
maybe we should go beat up qdot i think he has a working understanding of estim anyway.
:P

**Comment by FredTungsten** [comment]
He's probably busy writing a client-library in lisp 😄 

The whole e-stim thingy was never meant to be a big thing in ScriptPlayer, I just wanted to start something others could build upon and that's happened with the funstim PR.

**Comment by qwksilver** [comment]
this crash is resolved, finer control over devices is part of Audio Discussion
