### ISSUE TITLE
Vorze csv files

### ISSUE THREAD

**Issue by marcogroov** [FredTungsten/ScriptPlayer#162]
Hi,
I installed ScriptPlayer and this app are really good.
I would like to ask you if you provide to manage the csv files with the 3 values (timestamp, sense, power) because i have a Vorze Cyclone SA and i created many files but, i don't use the spin on every stroke because the Cyclone SA doesn't react well if the stroke is to short. I use only the spin on the long strokes or to simulate narrow penetration.
To be able to use my files, I need the 3 values of the Cyclone are managed 
Do you think you will evolve scriptplayer in this way ?
Many thanks for your answer
Regards
Marco

**Comment by FredTungsten** [comment]
Well, I don't have a Vorce to test this and it isn't even supported directly (only via Buttplug/Intiface) so I probably won't change anything - feel free however to send me a non-intrusive pull-request if you manage to resolve this.
