### ISSUE TITLE
Kiiroo KEON compatibility

### ISSUE THREAD

**Issue by Clasher31HD** [FredTungsten/ScriptPlayer#164]
Hey,

It would be nice, if you could add ScriptPlayer compatibility with the newly released KEON by Kiiroo.

Greetings Clasher

**Comment by FredTungsten** [comment]
Device support is more of a Intiface/Buttplug thing (I try to keep directly supported devices to a minimum).
Maybe @qdot will or is already working on it.

**Comment by qdot** [comment]
Done as of yesterday, Intiface CLI RS v16 in Intiface Desktop v19 supports the Keon, ScriptPlayer should work.

**Comment by zaph** [comment]
Sounds great that ScriptPlayer works with the new KEON!
I went ahead and installed Intiface Desktop v19 ... and have to admit ... how does it work to connect the KEON?
any tips or links as a guide?
BIG thanks at this point for your ScriptPlayer!!!

**Comment by zaph** [comment]
great and thanks for making the KEON work!
but it would be very appreciated if the KEON would show up as a device directly within ScriptPlayer.
just for convenience (and the KEON will replace the Launch).
anyway BIG thanks for the ScriptPlayer!!!

**Comment by qwertyqwert1234** [comment]
So is there a way to connect the keon to the scriptplayer?  Any simple instructions for this?  Am a newb to this whole scriptplayer thing.  Thanks.

**Comment by FredTungsten** [comment]
Download Intiface and the latest ScriptPlayer Beta, Connect Buttplug, Search for devices.
(I don't have one myself but that's how it should work)

**Comment by JadianRadiator** [comment]
"necro posting" because this issue is still around for me.
Intiface isn't seeing my Keon.
already have the latest Script Player beta installed.
