### ISSUE TITLE
Playlist abruptly stops when using Random Section + filled gaps

### ISSUE THREAD

**Issue by MarkusWo** [FredTungsten/ScriptPlayer#165]
Hey, I was the one who requested for the option of including filled gaps when you use the Random Section option. Ever since that was added I noticed a strange behavior when queueing up multiple videos in a playlist. Take the three example scripts in the attached zip file. A is a long script, while B and C are very short scripts. If you create a playlist where script A is followed by script B, script B will not play correctly and the playlist will just grind to a halt. If you have A followed by C the same thing happens. So the problem occurs whenever a very short video is loaded? Not necessarily. If you have a playlist A->B->C, then C will properly load and play even though it's just a few seconds long. So the problem isn't just with loading short scripts. The problem only occurs when a long scripts is followed by a short script (A->B and A->C). But there is no problem, whenever two short videos follow each other (B->C and C->B). Again, this only happens if using the include filled gaps option under random section. 

I've noticed problems with videos up to maybe 4 minutes length. I hope there is an easy fix for that. Otherwise I could also edit all my videos to be longer than 4 minutes but I hope there is another way. Thank You again!

[Scripts.zip](https://github.com/FredTungsten/ScriptPlayer/files/5432825/Scripts.zip)

**Comment by FredTungsten** [comment]
I think I found the problem, and can confirm your findings - the random section can be out of range of the video duration when the previously played video was longer, but only if "Fill gap after last action" is also active or the script is longer than the video.

Problem is that I need to load the script first, to determine which section to play based on 100 different settings.
I only know the new duration AFTER the video was loaded, which immediately updates the script fillers, but is too late for the random selection ....

Not sure how to solve this without major performance loss, but I'll probably figure something out (hopefully)

**Comment by MarkusWo** [comment]
Deactivating "Fill gap after last action" is a great fix for now! I definitely don't want to be responsible for major performance losses :-D
