### ISSUE TITLE
Is this a tool for pornhub remote interaction? 

### ISSUE THREAD

**Issue by Veryed-VS** [FredTungsten/ScriptPlayer#167]
Is this a tool for pornhub remote interaction? (sex toys) I want to write an Android program, but I don't know its API. Do you have any information for adaptation?

**Comment by FredTungsten** [comment]
No, this is completely unrelated

**Comment by qwksilver** [comment]
@Veryed-VS you might contact the dev for buttplug.io He's already done a lot of work with various web-to-api
