### ISSUE TITLE
Version 1.1.1 is loading always ini files by default instead of preferenced files 

### ISSUE THREAD

**Issue by Ut15h** [FredTungsten/ScriptPlayer#169]
Hi Fred,

when there are for a video an ini file (created by whirlig to save the VR settings) and a funscript file available in the same folder - for example
  
.\xyz.mp4
.\xyz.funscript
.\xyz.mp4.ini 

the scriptplayer always load automatically the ini file as script...not matter which player I'm using

Changing the preferences in the settings menue doesn't help. 

Regards
Chris

**Comment by FredTungsten** [comment]
Huh, I didn't realize Whirligig did that. I'll have a look - probably an easy fix (if I don't forget)

**Comment by FredTungsten** [comment]
I think that should do it. The problem you described no longer happens in the latest build.
The are potentially unwanted side-effects that I didn't think of - if you notice something please let me know.

https://github.com/FredTungsten/ScriptPlayer/wiki/Downloading-Beta-Builds

**Comment by Ut15h** [comment]
Great! Thanks for fixing that so fast...i confirm that the problme didn't happen no longer. 👍 
I really appreciate your great work. 
Regards
Chris
