### ISSUE TITLE
VideoDetailsPreview does not check the "In this directory" path for generated images

### ISSUE THREAD

**Issue by UnoriginalDevName** [FredTungsten/ScriptPlayer#174]
When using the "Save generated files...In this directory" feature, previews and heatmaps won't appear when hovering over videos in the playlist by default.  Manually adding that same path to the Settings > Paths list will fix this.  Ideally, this path would be searched by default, perhaps by being included in `GetRelatedFile()` similar to how `GetAdditionalPaths()` works now.

**Comment by FredTungsten** [comment]
Should both be fixed now - thanks for reporting
