### ISSUE TITLE
Instant crash when opening settings

### ISSUE THREAD

**Issue by 67858469** [FredTungsten/ScriptPlayer#176]
Whenever I click the settings button ScriptPlayer crashes. I've tested with the latest stable release and 1.1.1.332 on Windows 10 (insider preview 20279.1, hopefully that's not relevant).
[Crash.log](https://github.com/FredTungsten/ScriptPlayer/files/5786398/Crash.log)

**Comment by FredTungsten** [comment]
That's odd - apparently a problem with the Video Crop Preview.
Can you send me your Settings.xml, or at least these lines:

```
  <CropLeft>0</CropLeft>
  <CropRight>1</CropRight>
  <CropTop>0</CropTop>
  <CropBottom>1</CropBottom>
```
