### ISSUE TITLE
Handy Issues

### ISSUE THREAD

**Issue by ArranWool** [FredTungsten/ScriptPlayer#177]
The Input Mapping to raise the Maximum Speed instead affects
the minimum speed, so once you've lowered the speed there's no
way to raise it again without a lot of mouse work.

The settings in the speed and range tabs in any case do not seem to apply to the Handy, is that expected ? 

Tested on  beta from a few days ago.

p.s. thanks for the software, maybe setup a patreon account so people can make donations ?

**Comment by FredTungsten** [comment]
> The Input Mapping to raise the Maximum Speed instead affects
> the minimum speed, so once you've lowered the speed there's no
> way to raise it again without a lot of mouse work.

Coulnd't find anything wrong with this. Are you using the latest beta? Also: check if you maybe have the same button mapped twice.
