### ISSUE TITLE
unable to get any script working - figuring out

### ISSUE THREAD

**Issue by Zarackb** [FredTungsten/ScriptPlayer#18]
all i have to do is a save as?
as a text document?
or as a separate file type im not aware of?
i got the matching video - to - funscript name to pair however the script wont load correctly
ive tried changing the file type to java or visual studio something but refuses to work?
my feelconnect says on the top v.1.3.12rev.v4
is this the filmware type?
i havnt a clue how to update and the manual doesnt tell me either.

**Comment by FredTungsten** [comment]
Hi Zarackb,
The issue-tracker is not a forum or helpdesk, but is meant to provide information about reproduceable problems with the software. Try the [Troubleshooting](https://github.com/FredTungsten/ScriptPlayer/wiki/Troubleshooting) page for a couple of steps you can try. The [Scripts](https://github.com/FredTungsten/Scripts) repo contains instructions on how to download scripts.
