### ISSUE TITLE
Some scripts not working with Handy

### ISSUE THREAD

**Issue by MarkusWo** [FredTungsten/ScriptPlayer#181]
The Handy works flawlessly most of the time. I have a few scripts though that create an error message when you want to play them (see attached funscript files, had to rename them to txt because of github). The error message they produce says: "Failed to upload script to handyfeeling.com. Error converting file to Handy format. Could not parse data in funscript."

Curiously, the same scripts work without problem when using HandyControl 0.15.0. I use the option of uploading to Handyfeeling with both programs. All scripts works fine on HandyControl but they produce the above error message when I play them on Scriptplayer. I can fix the Scriptplayer error by using the local script host. I would prefer to continue using handyfeeling.com though as the local script host only works when I deactivate the windows firewall. Again it only happens on a few random scripts I have, not on all of them.

Maybe there is something HandyControl does when uploading that prevents these errors? @gagax1234 might you have some fix for this behaviour?

Thank you very much again.

[a.txt](https://github.com/FredTungsten/ScriptPlayer/files/6063208/a.txt)
[c.txt](https://github.com/FredTungsten/ScriptPlayer/files/6063209/c.txt)
[b.txt](https://github.com/FredTungsten/ScriptPlayer/files/6063210/b.txt)

**Comment by FredTungsten** [comment]
>Could not parse data in funscript

That's weird, SP doesn't upload funscript, but the already converted CSV.

**Comment by FredTungsten** [comment]
Every single one of those scripts uploaded without issues ("File is uploaded and ready for Handy to download").

3 causes I could think of:

- Temporary issue with handyfeeling? (unlikely)
- Someone else already uploaded a script with the same name? (added timestamp to script name)
- Does the original file name contain any special characters or non-alphanumerical characters? (I just pushed a new version that should fix that)

**Comment by MarkusWo** [comment]
I didn't make this connection earlier, but yeah all of those files contain some weird special characters. The new version has fixed it so that all of these work perfectly. Thank you again for this!
