### ISSUE TITLE
min command delay value not loaded properly after restart

### ISSUE THREAD

**Issue by TeaAndCookies** [FredTungsten/ScriptPlayer#185]
The "min command delay" value is saved when quitting the ScriptPlayer, but on the next load it's back to default even though UI still shows the saved value.

1) open ScriptPlayer and set min command delay to 10 ms, everything works nicely
2) close ScriptPlayer
3) open ScriptPlayer again, UI shows 10 ms delay, but in reality, commands are always sent with at least 166 ms delay
4) change the delay in UI to anything else and then back to 10 ms, everything works nicely again

**Comment by FredTungsten** [comment]
Should be fixed now

**Comment by TeaAndCookies** [comment]
Looks ok now, thanks.
