### ISSUE TITLE
Support for A10 PISTON SA (rends, vorze)

### ISSUE THREAD

**Issue by wondrrr** [FredTungsten/ScriptPlayer#186]
I can find the device but no scripts will run on it.

Same scripts works fine for both the handy and A10 cyclone SA.

SDK should be available here if it helps, im super noob at programming. https://www.vorze.jp/en/support/?id=faq

**Comment by FredTungsten** [comment]
ScriptPlayer doesn't support any Vorze device directly.

Try the latest beta of ScriptPlayer (https://ci.appveyor.com/project/FredTungsten/scriptplayer/build/job/8xdbt5a2fqprj5f7/artifacts) and the latest version of Intiface

**Comment by blackspherefollower** [comment]
The Vorze Piston isn't supported by the current version of Buttplug: it's waiting on some timing alalysis
