### ISSUE TITLE
connected and all but no movement? 

### ISSUE THREAD

**Issue by Theletha** [FredTungsten/ScriptPlayer#19]
the vorze 10 is connected via buttplug and script player is connected to buttplug but the vorze is not moving. not sure if im missing something?

**Comment by FredTungsten** [comment]
Unfortunately I don't have a Vorze to test this, but does it work when you select one of the generated sources (Slow, Fast, etc.) from the settings panel? A couple of other things to try: https://github.com/FredTungsten/ScriptPlayer/wiki/Troubleshooting

Btw, this is the issue tracker for the software and intended for more technical problems, so I'm probably the only one seeing this. You might reach more people on the RTS-forums here: http://realtouchscripts.com/viewforum.php?f=58 maybe someone else had a similar problem and already knows the solution to this one.
