### ISSUE TITLE
No Timestamp in the Playlist

### ISSUE THREAD

**Issue by Syunica** [FredTungsten/ScriptPlayer#191]
I saw someone had this bug before, and i also got it without knowing what i did wrong..
I freshly installed the Debug installer.
I also got K-Lite Codec Pack installed.
![Unbenannt](https://user-images.githubusercontent.com/20818376/123559620-689eb180-d79d-11eb-8df7-b314f6c2605e.PNG)
I also installed my K-Lite Codec Pack BEFORE ScriptPlayer.

**Comment by Syunica** [comment]
reinstalling Codec Packs changed nothing. I also tried a fresh windows install, just installed ScriptPlayer but it cant find the duration of the videos on my playlist. It shows the Duration when playing though.

**Comment by thesowismine** [comment]
I am also having this same issue.

**Comment by RugerLuger** [comment]
I am also experiencing this issue.

**Comment by FredTungsten** [comment]
In the latest beta, I've updated the library that reads the duration - maybe that fixed your problem
