### ISSUE TITLE
Web-Based Version not working correctly?

### ISSUE THREAD

**Issue by Nico-Src** [FredTungsten/ScriptPlayer#192]
I tried implementing the web based version with a project of mine but it seems the script just "randomly" sends commands to the kiiroo or fleshlight. Is there any fix or am i doing something wrong

**Comment by FredTungsten** [comment]
I honestly have no idea what you are talking about - could it be that you posted this in the wrong project?
If not - please elaborate.

**Comment by Nico-Src** [comment]
I mean the Web Scriptplayer. Everything works right for the positions and speed but the device doesnt receive the new inputs. I'm not that good at english I'm sorry if u can't understand.

**Comment by FredTungsten** [comment]
I am unaware of any "Web Scriptplayer".
You got the wrong project. I only made the desktop program "ScriptPlayer" for Windows - whatever you have going there is unrelated to my work and I can't help you with it.
