### ISSUE TITLE
Menu Items Vanishing or Glitching when Highlighted

### ISSUE THREAD

**Issue by ESDuna** [FredTungsten/ScriptPlayer#193]
I suspect that ScriptPlayer may have have an incompatibility with one of the recent Windows updates.  After the KB5004237 and KB4023057 updates, menu items seem to go blank when hovering the mouse over them.  Resizing the application window also results visual distortion of the text in the player window.  This was happening when I was on Windows build 20H2 but after reformatting to Windows build 21H1, the problem wasn't present until those two updates were pushed on.  Not sure if anyone else has seen this issue.

![image](https://user-images.githubusercontent.com/88066813/127249135-cbdd640d-d4e7-4df9-8a36-091875f89616.png)

**Comment by ESDuna** [comment]
I forgot to also mention that I though there might have been some startup applications causing this so I tried booting with all the non-Windows startup items turned off; the problem was still there.  This doesn't seem to be an issue in Safe Mode.

**Comment by FredTungsten** [comment]
Looks trippy 😃 
Without a way to reproduce it I can't fix it, but it *might* be caused by whatever app is adding those icons in the top right of the window - but that's just a guess (had something like that before in another app)

**Comment by ESDuna** [comment]
That's what my thoughts were too; I tried closing that application out and preventing it from running on startup but it was still happening even after a reboot.  If you don't mind me asking, is ScriptPlayer coded in C# and utilizing any vcredists of any sort?

**Comment by ESDuna** [comment]
Looks like I found the problem; turns out that it was some random audio service bundled with ASUS motherboards (something called the nahimic service or something).  When I disabled the service, the weird glitching issue completely stopped happening.  Who would've thought?

**Comment by FredTungsten** [comment]
> is ScriptPlayer coded in C# and utilizing any vcredists

C# - Yes
VC-Redists - No

> turns out that it was some random audio service

Wtf ... 😅

**Comment by ESDuna** [comment]
Mysteries of software wizardry.
