### ISSUE TITLE
a "video + script" speed option effecting playback? i guess?

### ISSUE THREAD

**Issue by assasinwar9** [FredTungsten/ScriptPlayer#199]
so i am wondering if there would be any possible way to basiclly have the video play in "slightly faster speed" and still keep the script in sync... 

this would likely benefit alot of ppl since it would strongly lessen the need for changing scripts to be faster/slower ... at least somewhat since you WOULD be playing the video faster/slower as well... but i myself would be very grateful for this!

something like vlc's playback speed "options" ... able to change from 1x to 1.100 etc and so on... preferable "leaving the option open" for up to 5x... even tho that would likely only ever be used in "very slow" videos lol

**Comment by FredTungsten** [comment]
That would be the "Playback Rate" in the right-side panel:
![image](https://user-images.githubusercontent.com/28461114/137343556-4ee68a2b-ee01-4534-a705-9b3bd9685767.png)

Works with devices that do not depend on timestamps (doesn't work with the Handy except maybe via Bluetooth)

**Comment by FredTungsten** [comment]
https://discuss.eroscripts.com/t/script-player-handy-over-bluetooth-firmware-3-much-better-expirience/31837

1. Download Intiface Desktop (aka Buttplug)
2. Configure Buttplug/Initiface in ScriptPlayer as needed
3. Make sure you have a BT 4.0/BLE capable BT Dongle
4. Upgrade Handy FW to Version 3
5. Long-press the connect button on your Handy to go into BT-Mode
6. In ScriptPlayer connect to Intiface and search for devices

<strike>The right side panel should show up when you hover your mouse on the ride edge of ScriptPlayer (like the playlist on the left side)</strike>

Ah, you found it :)
