### ISSUE TITLE
BUG: Crashes when reaching RedLine with speed Multiplier 

### ISSUE THREAD

**Issue by Theletha** [FredTungsten/ScriptPlayer#204]
Im using Script player with Butplug/init with a Vorze SA and i usually need to boost the speed of the scripts which i then use the built in Speed multiplier in script player. But when the native script is playing speeds that is natively close to 70-100 and script player trying to multiply these the player crashes. It's like if the value gets multiplied over 100 it crashes.

not sure where to turn for this issue if its script player or buttplug.

**Comment by FredTungsten** [comment]
Couldn't find anything on my end - looks like I'm properly clamping all values for Buttplug between 0.0 and 1.0
