### ISSUE TITLE
ScriptPlayer 1.1.1.368 fails to connect to ButtPlug via Intiface for Desktop

### ISSUE THREAD

**Issue by Hiroshi728** [FredTungsten/ScriptPlayer#205]
I’m running Windows10 (10.0.19043 Build 19043) via Parallels 17 on Intel MacBook Pro 13 inch (2016). I installed Intiface Desktop for Windows and the latest ScriptPlayer (ScriptPlayer-Debug-1.1.1.368.exe), but it fails to connect to ButtPlug via Intiface for Desktop. Once I click Devices > ButtPlug/Intiface > Connect, It would say "Connecting to ButtPlug (Attempt 1/10)" and crash. This issue doesn't occur with version Prerelease-1.1.1. (ScriptPlayer-PreRelease-1.1.1).

**Comment by lanniris** [comment]
Got the same problem too. I'm using 1.1.1.370. And the Intiface Desktop is V27.

**Comment by lanniris** [comment]
Found the solution. msvc runtime should be installed inorder to use scriptplayer. https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160

**Comment by FredTungsten** [comment]
Huh ... that's odd.
Thanks for figuring that out, I'll pass it along 👍

**Comment by FredTungsten** [comment]
Devs just confirmed, Buttplug client needs VC redistributables installed:
https://aka.ms/vs/17/release/vc_redist.x64.exe
