### ISSUE TITLE
"Next event in (thousands of seconds)" 

### ISSUE THREAD

**Issue by buschdogg** [FredTungsten/ScriptPlayer#208]
I'm trying to run CSV scripts locally for my Handy, but scriptplayer is reading the milliseconds listed in the CSV as actual seconds.... how do I change this?

**Comment by FredTungsten** [comment]
The CSV-Format in ScriptPlayer is an old Vorze Format, not the one for the Handy.

**Comment by buschdogg** [comment]
How do i convert mine to vorze?

**Comment by FredTungsten** [comment]
Honestly, you shouldn't - it's a terrible and outdated format that is very specific to the Vorze.
The most universal format supported by most players is "FunScript". 

I'll try to add the Handy CSV format to ScriptPlayer, but until now there was no need for it because everyone just uses funscripts.
