### ISSUE TITLE
Spelling mistake in FFmpeg tab of Settings.

### ISSUE THREAD

**Issue by KryptoTR** [FredTungsten/ScriptPlayer#209]
I know this is probably super low priority and probably a waste of my time to write it and your time reading it, but if there is a slight chance you care about spelling mistakes then the word "Automatically" is spelt incorrectly as "Autmatically"
![ffmpeg](https://user-images.githubusercontent.com/95548279/144724795-a95d919f-fb3b-4d0e-8d5e-1511b968aab5.png)

**Comment by FredTungsten** [comment]
Thanks, fixed it 👍
