### ISSUE TITLE
Working for 30 seconds then disconnecting

### ISSUE THREAD

**Issue by AdminJensen** [FredTungsten/ScriptPlayer#210]
I connect successfully but i am disconnected from my device after 30 seconds, here's the log:
r. 
Specific error for connector type: Tungstenite specific error: IO error: You could not make a connection because the target machine actively refused it.  (os error 10061).
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Buttplug.ButtplugClient.<ConnectAsync>d__44.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   ved ScriptPlayer.Shared.ButtplugAdapter.<Connect>d__12.MoveNext()
   
   Any ideas about what might cause this?

**Comment by FredTungsten** [comment]
Not really, I had something similar once after updating Intiface.
What solved it for me was completely uninstalling Intiface and installing a fresh copy.
