### ISSUE TITLE
BUG: Can't edit paths

### ISSUE THREAD

**Issue by qwksilver** [FredTungsten/ScriptPlayer#212]
I can't change a path to do a \* for all subdirectories.  i've tried a variety of ways, and none have worked. thanks

**Comment by FredTungsten** [comment]
Ah, I see - that probably broke when I changed the text field to a proper directory picker.

Manual workaround:
Open ``%AppData%\ScriptPlayer\Settings.xml`` with a text editor and scroll down to the paths (AdditionalPaths) to edit the path.

Should look something like this:

```
<AdditionalPaths>
    <string>D:\Path\*</string>
</AdditionalPaths>
```

**Comment by qwksilver** [comment]
ok, I had found and updated the config file shortly after, just thought you should know about the problem.

**Comment by FredTungsten** [comment]
Should be fixed now
