### ISSUE TITLE
Feature Request: Mark script for deletion

### ISSUE THREAD

**Issue by MarkusWo** [FredTungsten/ScriptPlayer#213]
Hello!

I am using the Playlist to shuffle through my collection of funscripts whenever I just want to spend an hour. My playlist is now about 1200 files and I need to cut it down. I'd like to be able to delete a file (or rather the video, funscript + any thumbnails etc.) when I realize that I don't want to have this in my playlist anymore. Maybe a hotkey to "delete current video+script" or something like that would be a great solution. 

Up until now, I have been going File -> Show loaded files and hit [CTRL]+C. That puts a lot of text into your clipboard that you can then paste into a textfile and then come back to deleting the scripts after you're done. It's a bit messy and hard to do with one hand though. If a hotkey to just delete a file is unfeasible, maybe some way to make it easier (one-handed) to copy the currently loaded funscript's filename into your clipboard could be another solution. 

Obviously this isn't a super urgent request, but I've been wanting this for a while now. More ways to manage an ever growing playlist (I know I'm addicted :-)

**Comment by FredTungsten** [comment]
Simply right click on any entry and select "Delete (permanently)"  to permanently delete the video and all related files (script, thumbnails, preview, etc.)

There are assignable hotkeys for that (bottom of the list), but permanently deleting a loaded file wont work - you could however move it to a "file to be deleted folder" first.

**Comment by MarkusWo** [comment]
Oh wow I didn't know there was such an extensive right-click menu in the playlist. That's awesome! Works fine for me, thank you.
