### ISSUE TITLE
ScriptPlayer got wrong/messy filename when load non-English video file in external player(MPC-HC)

### ISSUE THREAD

**Issue by lanniris** [FredTungsten/ScriptPlayer#215]
I connect the scriptplayer with MPC-HC64, and load a video file which has some Japanese words in its name. But scriptplayer get the wrong filename and cannot find the script file. It looks like a messy code error. Maybe something to do with ASCII or UTF8? I guess...

![image](https://user-images.githubusercontent.com/1030028/149210452-f6e04a11-f0e4-4c28-af44-8f90ee799b66.png)
![image](https://user-images.githubusercontent.com/1030028/149210527-98f3c1eb-70c6-44ba-8264-afe1b969a90d.png)

**Comment by FredTungsten** [comment]
Seems to be an encoding issue with the library I use to parse the MPC WebInterface, even though every component involved should use UTF-8. I think I found a workaround that solves this in v1.1.1.372:

https://ci.appveyor.com/project/FredTungsten/scriptplayer/build/job/no6bi6k9oa4yw46t/artifacts
