### ISSUE TITLE
DeoVR no video playback but connected?

### ISSUE THREAD

**Issue by Ccohen68** [FredTungsten/ScriptPlayer#217]
I am trying to stream video from ScriptPlayer on Windows Desktop to Oculus Go using DeoVR (on the Oculus) as the video player.  On the desktop, ScriptPlayer says it is connected to DeoVR (and so I see no video on desktop just message it is connected).  However, when I am in the DeoVR app on the oculus, I see no signs of a connection (and the video doesn't play, even though ScriptPlayer on the desktop still says "connected").  DeoVR functionality on Oculus remains normal; I can go to internet or local files screen, but still no sign of connection or video that I am trying to play on ScriptPlayer.  Perhaps a clue or maybe normal: ScriptPLayer shows me that there is an mp4 and script loaded, and if I move mouse pointer over the bottom time scrub bar it shows me the video thumbnail but the timer #s to the right continue to show 0:0000.  What am I missing? and thanks for the assist

**Comment by Orgasmscience** [comment]
I think this is normal, DeoVR will indeed not show you anything about being connected - it just silently exposes its timeserver and that's it. If you hit play within DeoVR, the script should be starting playing on your windows machine. I can't test it right now, but the scrub bar is indeed inoperable in remote mode. The play/pause button should still work though, but only if your Go is actually on (it'll go to sleep mode obviously as soon as you take the headset off).
