### ISSUE TITLE
audio/video timing off for 4K videos

### ISSUE THREAD

**Issue by thesowismine** [FredTungsten/ScriptPlayer#218]
Every 4k video i have tried to play results in the audio being far ahead of the video. Offsetting the audio doesn't even seem to work.

I've tried the same videos in handyfeeling and scriptaxis where there were no issues.

Is there anything i can do to fix this?

**Comment by FredTungsten** [comment]
The only thing you can try is installing different codec-pack ([e.g. one of these](https://github.com/FredTungsten/ScriptPlayer/wiki/Troubleshooting)). The audio offset feature is for the e-Stim audio, not the regular audio.
