### ISSUE TITLE
%20 as space

### ISSUE THREAD

**Issue by tradertorrent** [FredTungsten/ScriptPlayer#225]
When launching a video in DeoVR on Android that has space in filename Scriptplayer can't find the script automatically.
Scriptplayer says that it can't find the script and the error shows that all spaces are replaced with %20
Scriptplayer runs on Windows and have the scripts in a Samba share on Linux.
DeoVR plays the video from Apache Webserver running on Linux.

**Comment by FredTungsten** [comment]
Sounds like a bug (or technical necessity) of the DeoVR/Apache combo.
I'll add a "url-decode filenames" feature in the players settings, that should take care of that.

**Comment by FredTungsten** [comment]
Done - latest beta has an additional option in the "Players" section to decode such filenames
