### ISSUE TITLE
Is there a reason why SP targets v4.6.2?

### ISSUE THREAD

**Issue by SomeoneFarAway** [FredTungsten/ScriptPlayer#226]
As the title says, is there a specific reason v4.6.2 is targeted when 4.8 should be used?

I tried building for 4.8 and could not find anything wrong.

I am also preparing for a PR for a feature I want (quick favorites, playlist independent).

**Comment by FredTungsten** [comment]
No specific reason - I just don't keep the framework and packages up-to-date as it's not really as "rewarding" as adding new stuff. But yes, it might be time to do that again - I'll try to get that done next week(-ish) 😉

**Comment by FredTungsten** [comment]
Done
