### ISSUE TITLE
MPC-BE support

### ISSUE THREAD

**Issue by Enissay** [FredTungsten/ScriptPlayer#230]
MPC-HC is no more under development, can you support MPC-BE instead ?

https://mpc-hc.org/

https://sourceforge.net/projects/mpcbe/

**Comment by FredTungsten** [comment]
As far as I can tell it already works. Did you encounter any problems?

**Comment by MemeMan404** [comment]
> 

I just tested it for myself, it seems to work for me too. I'm guessing they made the issue before they tried it out. Too bad no MPV support 😞

**Comment by FredTungsten** [comment]
> > As far as I can tell it already works.
> 
> I just tested it for myself, it seems to work for me too. I'm guessing they made the issue before they tried it out. Too bad no MPV support 😞

Has been requested before, I might get around doing that sometime before 2030 (no promises):
https://github.com/FredTungsten/ScriptPlayer/issues/200
