### ISSUE TITLE
action does not follow scripts with fast movement

### ISSUE THREAD

**Issue by williamioniana** [FredTungsten/ScriptPlayer#231]
Version 1.1.1 Windows 10
Intiface -> Scriptplayer -> The Handy
Everytime I load up a script with high series of commands in a tight time frame such as vibrations, The Handy seems to skip a few commands. Funscript.io and Handyfeelings both do not have this problem, I'm not sure if it has something to do with bluetooth.

**Comment by FredTungsten** [comment]
Try setting the min. command delay lower (in the current beta version it can be set to as low as 1 ms)

**Comment by williamioniana** [comment]
Thanks, turns out I was using an outdated version, now it works perfectly, love the work btw
