### ISSUE TITLE
ScriptPlayer VideoSync

### ISSUE THREAD

**Issue by CrummyPaper80** [FredTungsten/ScriptPlayer#232]
Hello, I didnt know where else to put this, is there a way to create a script using ScriptPlayer or is that not implemented yet? I would also like to ask for help compiling it if you can since i've heard that that would allow it. If this isn't the place to ask this then could you direct me in a better place?

**Comment by FredTungsten** [comment]
This would be a better place to ask:
https://discuss.eroscripts.com/c/help/12
