### ISSUE TITLE
add Potplayer

### ISSUE THREAD

**Issue by rampofoxx** [FredTungsten/ScriptPlayer#241]
Hi,

I hope I'm doing this right.

could you please look into adding Potplayer to the supported video players?

this video player is very optimized for basically everything **especially** to play VR videos on a 2D screen
additionally, it has a lot of features and is customizable.

I know you have Whirligig for VR but unfortunately, it doesn't work great for touchscreens, it's a bit buggy.

here's the link for the official website https://potplayer.daum.net/
Please let me know if you have any questions regarding its usage.

thank you

**Comment by IIEleven11** [comment]
Was looking for potplayer API. Doesnt look like its open source but they do have an add on functionality with angelscript. https://www.angelcode.com/angelscript/

I did find this potplayer api but its 5 years old and dont know how much help it would be.
https://www.openhub.net/p/potplayer

I am willing to help but im a 2nd year CS student and my knowledge with API's is limited. If you want the help and are willing to point me in the right direction I could give it a shot.

**Comment by FredTungsten** [comment]
Sorry, but that doesn't help.
I have no problem accepting a clean pull request with working code, but I can't just integrate a 3rd party player with no official API support.
