### ISSUE TITLE
Delay video playback until device has finished downloading script

### ISSUE THREAD

**Issue by trassshhub** [FredTungsten/ScriptPlayer#242]
Currently ScriptPlayer would start the playback immediately when video/funscript file is open/drag-and-dropped.
When using the Handy, I always have to stop the playback manually and wait for the Handy to finish downloading first.
It would be nice to have an option to delay playback until the device has finished downloading the script, or at least an option to disable immediate playback on open.

**Comment by FredTungsten** [comment]
Totally agree - I'd like to have a feature like that myself, but it's a bit complicated to cram it into all the existing logic.
I'm definitely take another look someday, but probably not soon.

**Comment by FredTungsten** [comment]
I forgot to mention it, but I added this in a previous version
