### ISSUE TITLE
Feature Request - Tap tempo

### ISSUE THREAD

**Issue by adamxex** [FredTungsten/ScriptPlayer#246]
Story: Allow user to sync the Pattern speed to the BPM of the song .

- Hot key for a Tap Tempo
- Sync the pattern speed to the rate of the user key press

- Additional considerations:  Position. Is the position adjusted to compensate for top/bottom on tempo

thank you

**Comment by FredTungsten** [comment]
Nah, sorry but there are already tools for script creation out there - I'm not opening that can of worms again 😅 

https://github.com/OpenFunscripter/OFS
