### ISSUE TITLE
Help compiling code in Visual Studio

### ISSUE THREAD

**Issue by delorean57** [FredTungsten/ScriptPlayer#249]
Hello, i'm trying to compile the code in visual studio, i want to make some tests to see if i can add a new player (GoPro VR player) but i got a lot of errors when i try to compile, I don't use Visual Studio or C# usually , so, i'm not very familiar with the process, I just cloned the repository and went to build, i have installed windows 10 SKD and .net framework 4.8.... what am i missing? 
Please, help
By the way, the player i'd like to test sends info via UDP, so, i think would be similar to Samsung VR.

![imagen](https://user-images.githubusercontent.com/123653937/214895602-da0f7d01-00c5-4ffd-84b0-1ddd008c14e5.png)

![imagen](https://user-images.githubusercontent.com/123653937/214921801-30bdf850-39e4-4d38-8453-ab807dfb5f40.png)

**Comment by FredTungsten** [comment]
Since this seems to be the most common issue over and over again, I just removed native support for BLE devices. 
Should be a lot easier to compile ScriptPlayer without fiddling with MD-files, SDKs and other nonsense.
Hope this helps

**Comment by delorean57** [comment]
Thank you Fred, i just did a pull and now it compiles without problem.
