### ISSUE TITLE
Improve Vorze conversion

### ISSUE THREAD

**Issue by FredTungsten** [FredTungsten/ScriptPlayer#25]
It kind of works but not ideally, maybe have a deeper look at this: http://realtouchscripts.com/viewtopic.php?f=59&t=5856

**Comment by Thanny0ther** [comment]
If you need any clarification on the algorithm, or some actual code, let me know.  I've not spent a lot of time looking at C#, but I know my way around C++ well enough.

**Comment by FredTungsten** [comment]
Will do, thanks. I'll probably start working on this somewhere around January/February.

**Comment by FredTungsten** [comment]
Clodes Duplicate #29

**Comment by trejkaz** [comment]
Came here via finding #29 on Google. I'm using Vorze CSV for input and an actual Vorze device for output, and was surprised that it's converting at all.

**Comment by FredTungsten** [comment]
It's probably not working too well because I don't have a Vorze and didn't receive a lot of feedback either.

**Comment by FredTungsten** [comment]
On the device side, Buttplug is doing all the heavy lifting - as you've guessed it tells ScriptPlayer that the deivce supports VorzeCommands but also generic movement commands, which is what I'm using. I've given up on trying to convert the commands themselfes because that parts seems to work alright. I should probably remove the empty functions I never finished.
