### ISSUE TITLE
Request - Toggle/Show Script Lines

### ISSUE THREAD

**Issue by Barbadozer** [FredTungsten/ScriptPlayer#253]
With a script playing, when hovering over the playback at the bottom of the screen, a preview picture of the video and the script lines/curves are shown. I'd like to see these line/curves at all times or have a toggle to show/hide them. This would help when debugging and testing custom scripts.

**Comment by FredTungsten** [comment]
All you need already exists in the right-side panel's debug section:

![image](https://user-images.githubusercontent.com/28461114/223211243-fe86ed66-02b2-4543-8912-fca54b4e6084.png)

**Comment by Barbadozer** [comment]
Oh! Show Script Positions is actually what I was after. Thank you!
