### ISSUE TITLE
Unable to determine version

### ISSUE THREAD

**Issue by kimmmjg** [FredTungsten/ScriptPlayer#279]
![image](https://github.com/FredTungsten/ScriptPlayer/assets/141753877/1b7c5cf0-1969-49c3-9f01-6f94a30eae60)

When I start the program, the phrase 'unable to determine version' is displayed.

And even if I try to link it with Handy, it doesn't work.

**Comment by FredTungsten** [comment]
The version gets read from github - which is weird that it doesn't work for you as you clearly have access 🤔
