### ISSUE TITLE
Feature Request: Autoblow AI Ultra API support

### ISSUE THREAD

**Issue by interbiznw** [FredTungsten/ScriptPlayer#282]
The new autoblow AI Ultra has an API that you can use to control the device and run funscripts, maybe this could be integrated so one could play videos/scripts from this instead of using their web interface

https://latency.autoblowapi.com/documentation/static/index.html

**Comment by whatcom383** [comment]
https://github.com/whatcom383/autoblow-ultra-playground

**Comment by FredTungsten** [comment]
I don't have a device to test, so I can't add it myself, but if someone sends me a clean implementation via pull request that doesn't break anything else I'll merge it.
