### ISSUE TITLE
Unable to connect to Handy Locally

### ISSUE THREAD

**Issue by zerocoolcloud** [FredTungsten/ScriptPlayer#287]
![image](https://github.com/FredTungsten/ScriptPlayer/assets/166425322/6cbb90c5-d97f-4d0c-8fc1-62c8aa4d0714)

I have been using Handy for months without any issue. 
But one fine day, it just failed to connect locally. It used to be able to connect locally without problem.

I tried re-installing, reconfiguring, going through setting back and forth, but still can't figure out what went wrong.
Handy is connected with the same network as my laptop. Even shown that handy is connected to my laptop successfully. But script can't seem to be loaded. Error appearing Device Timeout. This issue only happens with Local Settings.

No issue when I connect via handyfeeling.com.
Also, no issue with my other laptop (yes, I have 2 laptops). All settings are exactly the same, but one just refuse to work. 
I have also tried pinging handy with my pc. No issues too. There is direct connection. 

Anyone out there with a solution?

**Comment by Tsumuya** [comment]
Same here

**Comment by zerocoolcloud** [comment]
A quick update here. I manage to find out the cause of the problem and solved it. 
Appears that it has to do with windows firewall blocking port 80.

To resolve, go to windows firewall settings. Then, add in new rule. Add in Port 80 and enable it.
Problem solved!

**Comment by zerocoolcloud** [comment]
Problem solved by adding port 80 into windows firewall rule.
