### ISSUE TITLE
unable to play anything after windows reinstall

### ISSUE THREAD

**Issue by glodomorrapl** [FredTungsten/ScriptPlayer#289]
i've been using ScriptPlayer for a while and it worked great, but i had to reinstall windows for an undisclosed reason. now i'm on windows 11 23h2 - just as i was before - and i'm unable to get ScriptPlayer to play anything. no matter what codec (h264/h265/av1) and what container (mp4/mkv), it's just always a black screen.

i have followed the [troubleshooting](https://github.com/FredTungsten/ScriptPlayer/wiki/Troubleshooting) page. the "media feature pack" doesn't seem to be available on windows 11 anymore, so i've tried k-lite codec pack, first the standard version, then the full. nothing changed. i did not try cccp because it's an old abandoned project that should probably be removed from the wiki, and the "VRP support page" no longer leads anywhere.

and it's just ScriptPlayer causing me a headache. whether i use heresphere, windows media player, MPC-BE or media player classic included in k-lite, every single file i have plays perfectly fine, no issues whatsoever. i'd try to generate some sort of log from ScriptPlayer to maybe get a clue on what's going on, but i have no idea how. the "playback using external player" functionality doesn't quite fit my use-case so i'd really like to get the embedded player working again. 

any help would be highly appreciated. tested on ScriptPlayer 1.2.0 and 1.2.1.

**Comment by FredTungsten** [comment]
> the "media feature pack" doesn't seem to be available on windows 11 anymore
It should be according to Microsoft:
https://support.microsoft.com/en-us/windows/media-feature-pack-for-windows-10-11-n-february-2023-2aaf89b8-f9d3-4322-98d0-612c9bea9c01

Maybe they just renamed it since the release

**Comment by glodomorrapl** [comment]
i forgot to post a solution - i was missing "windows media player legacy" for some reason. installable through optional features. everything works fine now.
