### ISSUE TITLE
Improve CSV (Vorze script) playback

### ISSUE THREAD

**Issue by realcumber** [FredTungsten/ScriptPlayer#29]
It seems that Scriptplayer isn't sending the full detailed commands in a CSV script for playback using the Vorze.
You can see this by using the same exact CSV file and compare playback to the Script player and the Vorze player.  
The Vorze player plays back many more detailed and accurate movements 

Vorze player can be found here: 
https://vorzeinteractive.com/download

**Comment by FredTungsten** [comment]
I don't have a Vorze to test this but it's most likely because every script format is converted to FunScript first. I've been looking into native playback but that might take a while until it's done. Until then I hope to improve the conversion itself (Issue: #25)

**Comment by realcumber** [comment]
Yes that then makes perfect sense as to why it seems off.  Improving the conversion itself sounds like the definitely better priority agreed

**Comment by FredTungsten** [comment]
Duplicate / Closely Related to #25
