### ISSUE TITLE
Fleshlight Launch 'Connect Launch Directly' Missing from Devices Tab in ScriptPlayer v1.2.1

### ISSUE THREAD

**Issue by dcopher** [FredTungsten/ScriptPlayer#293]
Hi Team,

First of all, thank you for your continuous efforts and dedication to making ScriptPlayer an amazing software! I’ve been a long-time user and truly appreciated the experience with version 1.2.0.

However, I noticed that in version 1.2.1, the Fleshlight Launch device is missing from the Devices tab. The Launch is a fantastic addition to ScriptPlayer, and I would love to see it supported again in a future update.

Your work is greatly appreciated, and I hope this feature can make a return. Keep up the amazing work, and thank you for all that you do!

**Comment by FredTungsten** [comment]
Hi,
Launch is still supported via [Intiface](https://intiface.com/), native support will not be back.
BR,L
