### ISSUE TITLE
ScriptPlayer not responding

### ISSUE THREAD

**Issue by gxriderr** [FredTungsten/ScriptPlayer#30]
The player crashes on Connect Launch directly. It has worked before, but 8 out of 10 times it will crash and say "ScriptPlayer not responding". I am using most up to date Windows 10.

**Comment by FredTungsten** [comment]
Well, that shouldn't happen. Couple of questions:

- What BLE Dongle are you using and have you checked [this list](https://github.com/FredTungsten/ScriptPlayer/wiki/Devices#ble-dongle-chipsets)?
- What's the error message/stack trace in the EventViewer?
- Are you using the latest release, or a build from AppVeyor?
- If you are not using the [lastest build from AppVeyor](https://ci.appveyor.com/project/FredTungsten/scriptplayer/build/job/86elvnke8p8lsvgo/artifacts), please try it with that and post the crash log (%APPDATA%\ScriptPlayer\Crash.log)

**Comment by gxriderr** [comment]
- I am on a laptop with a built in Bluetooth. It has connected 2-3 times before to the Launch.
- Error message in EventViewer:

> Faulting application name: ScriptPlayer.exe, version: 1.0.3.69, time stamp: 0x5a36ba31
> Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x2cd1ce3d
> Exception code: 0xe0434352
> Fault offset: 0x001008b2
> Faulting process id: 0x2428
> Faulting application start time: 0x01d379cffb65f488
> Faulting application path: E:\Program Files (x86)\ScriptPlayer\ScriptPlayer.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 41b2fd29-3ca3-474b-845e-9e3dfd3967fa
> Faulting package full name: 

And .NET runtime error:

> Application: ScriptPlayer.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.NullReferenceException
>    at ScriptPlayer.Shared.LaunchBluetooth+<BleReceived>d__10.MoveNext()
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
>    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


- I am using the latest release. I've reinstalled with latest build with AppVeyor. Crash log:

> Object reference not set to an instance of an object.
>    at ScriptPlayer.Shared.LaunchBluetooth.<BleReceived>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
>    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Thanks

**Comment by FredTungsten** [comment]
Damn, of course it had to be an anonymous or async method ...
Does this happen immediately after clicking connect or does it take a while? Does the blue led on the launch keep blinking or does it briefly connect?

I've added a couple of additional checks ([new build should pop up here](https://ci.appveyor.com/project/FredTungsten/scriptplayer/build/job/50qf8oyyij898g74/artifacts)) but those are pretty much a stab in the dark I'm afraid.

**Comment by gxriderr** [comment]
It will happen immediately and the launch would keep blinking.
I just downloaded the new build and actually so far so good. Will post here if it crashes again.

Thanks for your help!

**Comment by FredTungsten** [comment]
No more reports for over a month, I take that as a good sign then :smile:
