### ISSUE TITLE
Script download broken

### ISSUE THREAD

**Issue by kometo** [FredTungsten/ScriptPlayer#31]
The link "from me" in wiki script page is broken: https://github.com/FredTungsten/ScriptPlayer/tree/master/Scripts

**Comment by FredTungsten** [comment]
Thanks, I fixed it (Scripts are in a separate repo now: https://github.com/FredTungsten/Scripts)

**Comment by kkomelin** [comment]
@kometo How can I contact you? I might have an offer for you.

@FredTungsten I apologize for using the comments for personal stuff but I cannot find a way to contact @kometo otherwise. I promise not to "spam" you anymore.
