### ISSUE TITLE
Build instruction

### ISSUE THREAD

**Issue by i3jjnc68emm** [FredTungsten/ScriptPlayer#36]
I tried to compile the source using VS 2017 but there are a lot of reference issues regarding Windows.Devices.Bluetooth and similar. These are not covered by nuget packages nor included in default VS installation.

Could you please add a short build instructions with all requirements? Thanks for the amazing app!

**Comment by FredTungsten** [comment]
``Windows.Devices.Bluetooth`` is part of a WinRT library that only works on Windows 10 (maybe 8.1+) If you simply want the lasted build, you can grab an up-to-date installer on my [AppVeyor](https://ci.appveyor.com/project/FredTungsten/scriptplayer)

**Comment by i3jjnc68emm** [comment]
I don't want the latest build, I want to add my own modifications to the source. I'm using Windows 10 and VS 2017 professional and got installed the desktop environment package and UWP development package. But it still  throws me lots of reference missing errors.

Can you provide a link to the runtime package that is required? Or if its pre-installed on Windows 10 then the path where I can find it?

**Comment by FredTungsten** [comment]
Mine is at ``C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0\Windows.winmd`` and is part of a ``Windows Software Development Kits`` or ``Windows 10 SDK``. There are probably newer versions available.

**Comment by i3jjnc68emm** [comment]
Ah, Windows 10 dev kit is required. Ok thank you Fred!
