### ISSUE TITLE
Samsung VR (GearVR) Sync feature

### ISSUE THREAD

**Issue by RickNLX** [FredTungsten/ScriptPlayer#40]
I would love to see ScriptPlayer sync with the GearVR (like it does now with VLC and Whirligig). This could be achieved by using the presentation mode of the Samsung VR app. I sends out udp commands using port 5000: Load, Pause, Play, Stop. I already made it accessible on my laptop  (oldschool VB programmer...), but unfortunatly i can not load your C# project in visual studio 2017.....

It would be really great if you would consider making this possible, and i would be glad to help you with an example of the commands or anything else offcourse.

Commands overview: https://samsungvr.com/portal/content/presentation_mode

Or maybe you could help me out loading your C# project here in VS2017, so i can add it myself :)

You have done a great job with this piece of software, it works like a charm! Only thing that is missing is GearVR support at this point. VLC does not have VR capability's yet (at least not on android)

**Comment by FredTungsten** [comment]
Since I don't have a Samsung Phone this would be hard to test for me, but I can definitely help you with the VS2017 issue. (Maybe it's the same as this one: https://github.com/FredTungsten/ScriptPlayer/issues/36 ?) What's the problem / how can I help?

Also, if you upload your VB code to GitHub I can take a look and prepare a bit of code for you to tinker around with (and eventually turn into a Pull Request of course :smile:).

**Comment by RickNLX** [comment]
Would be nice to look into your project to see what i could do. In #36 it seems to be the missing installation of Windows 10 SDK. I have it installed. When i load the project,scriptplayer.shared. remains unloaded. See screenshot....

I could upload some vb code, but that code only controls the GearVR app if connected within the network, so if you do not have a gearvr it would be hard to test and tweak.... If i cannot get your app to run in VS, then i will do that, maybe you could create a test app that i could test :)

![scr](https://user-images.githubusercontent.com/36103484/35768646-8293ed6e-08ff-11e8-9f80-095e0e734468.jpg)

**Comment by FredTungsten** [comment]
Hmm ... looks like you are missing some files or accidentially unloaded the project. VS2017 has git support integrated so you should be able to just clone the entire project to a local repostitory. After a rebuild to download all NuGet packages you should be good to go.

**Comment by FredTungsten** [comment]
By the way: Once you get it running, a good place to start would probably be an existing TimeSouce (e.g. (VlcTimeSource)[https://github.com/FredTungsten/ScriptPlayer/blob/master/ScriptPlayer/ScriptPlayer.Shared/TimeSource/VlcTimeSource.cs]) and just modify that one to target GearVR.

**Comment by RickNLX** [comment]
I got it running now :) Thanks for your help, i really appreciate it! I think the Whirligig code comes in very close to what i am trying to accomlish. I will try to make some changes, like the TCP protocol to UDP. I see that InterpretLine is the main thing to look at after that. I have some free time tonight, so i will see what i can do here :) (though C is not my programming language, i think i can work this one out)

**Comment by RickNLX** [comment]
Little update on this one: It was a bit of a struggle to convert the TCP to UDP, but i managed to figure it out and will only require a port number (no ip needed if the phone is wifi connected to the home network) because it listens to all devices on that port) 

I am almost done changes the InterpretLine values, except for the _timesource.Setposition (when seeking through a file) Does it expect the time in milliseconds/seconds/time? The SamsungVR app sends it out in milliseconds (like "123555")

Still got work left on enterpreting the loaded file, when it's on the phone or mediaserver it has to somehow match files on the computer for haptics and video (to get the totaltime only). I am now testing it with a local "non" matching file with a lot of length, just to bypass errors for now :)

**Comment by FredTungsten** [comment]
SetPosition expectes a TimeSpan. If you have the current position in milliseconds, you can convert them to a TimeSpan with ``TimeSpan.FromMilliseconds(milliseconds)``. As for the files: There is a setting called ``Paths`` where you can put the scripts. When ScriptPlayer can't find the script in the same folder (which in this case is basically guaranteed) it will look in all specified local paths too.

**Comment by RickNLX** [comment]
Thanx. That works like a charm :) I will add some paths to see if that works. In the InterpretLine void, i changed the file from the actual video, to the haptic file (.meta) I seems te be working ok and get the length of the haptic file (instead video file), so i can go from there without actually having the video file on the computer. I will do some testing later this evening with an FL Launch connected, see how it syncs up in realtime. 

My guess is that local files on the phone will work pretty nicely. The only "obstacle" now, is the fact that when running files from a mediaserver, the time will go out of sync because there are (strangly enough) no commands for signaling when buffering a video stream and pause scriptplayer during that. 

I contacted the Samsung VR develloppers if they would be so kind to add those commands (Loading and Resume). And from previous contacts with them, i have some good hope that they will look in to it.

**Comment by RickNLX** [comment]
I had some major CPU spikes during recieving the UDP data from the ports. I found out i did not program the Asynchronic void efficently. Working on this project, improves my C# skills. I got that fixed now, so it runs smooth. When switching/ending the connection i kept getting errors. Took some time to figure that one out too :) 

I did some testing: Local files on phone run pretty much in sync. Files from a media stream run in sync too, when hitting pause, when the video show the "loading" image and then play when done. I ran into some errors while testing and fixed them on the spot. Samsung aleady responded to me that they will look into adding 2 extra commands: Loading and Resume. When they update the app, i can easily add that to the Line Interpreter, so both streaming and local video's will be synced perfectly. Hopefully they will add it in a couple of weeks, so i can add it before releasing the code.

For now i have set the position with a little offset of -0.5 seconds for spot on syncing, not sure if that will depend on bluetooth controller speed and cpu speed though (probably; yes)....

I have added a path to the app in runtime, and like you said it picks up the selected haptics file from that location. I also found out that if i send a filename with the wrong extension, your code automaticly seeks for the right extension. Saves a lot of extra work!

Still got some details to work on, but it seems i am 75% done, so it progresses nicely so far!

**Comment by RickNLX** [comment]
If have done some changes to simplify code and some testing, and added catching exceptions etc. I could upload the SamsungVRTimeSource.cs, so you could add some stuff to the ScriptPlayer if or when you have the time for it :-):

****Add Samsung VR to Playmode and Settings menu** Text when not connected "Start Samsung VR and make sure 'Presentation mode' is activated in the settings menu.

**Create a SamsungVRConnectionSettings.cs**** It needs an IpPort setting only (default=5000) 

After that would be done, i will update my project and give it some proper final testing and add the IpPort setting to the script. (it is now set to 5000, but should be a setting, so i it could be changed) 

Hopefully Samsung's dev team will update the app on my request by adding the extra command's, but i do not have a clue how long that would take. I have contacted them about that, if they could give me an estimate on it. (day, weeks, months?). If it would take longer then your next release date (do not know what you have planned) the script could still be released but with an instruction on how to handle "streaming" video's (set autoplay to false and press pauze when browsing through a video and when done loading, press play) Offcourse i could write a short instruction about usage for you to add to your wiki :)

**Comment by FredTungsten** [comment]
That's great. I'll try to create a stub with all the necessary details (Playback Mode Menu, Settings, etc.) tomorrow (or at least this week). You can either upload your code and post a link here, or (once I'm done with the preparations) fork the repo, add your code and create a Pull-Request, whichever you prefer.

As for my next release: I have a lot of experimental stuff in the current build so I don't know when the next release will be, but since [AppVeyor](https://ci.appveyor.com/project/FredTungsten/scriptplayer) automatically creates a setup of every commit, distributing a beta shouldn't be a problem.

**Comment by RickNLX** [comment]
There are still some whirligig references in this code because i reprogrammed the whirligig time source.

Here is the code.
[SamsungVRTimeSource.cs.txt](https://github.com/FredTungsten/ScriptPlayer/files/1704917/SamsungVRTimeSource.cs.txt)

Rename .cs.txt to .cs offcourse. If you need something else or need info, please let me know!

**Comment by FredTungsten** [comment]
I've integrated your code and made a couple of changes (I hope it still works).
I also tried to add the playback commands detailed [on this site](https://samsungvr.com/portal/content/gear_vr_synchronization), so maybe that works too.

Unfortunately the documentation is far from complete but at least it's entertaining 😄:
>the following string placed in the user.cfg file would change the UDP port used to **4500**.
>udp-port:**6000**

If you would like to add/change anything it would be best to do that with Pull-Requests from now on.

**Comment by RickNLX** [comment]
I have testes the new code :-) You have deleted the "exclude headpos2 command" from **OnUpdData**, this will try to fill up the debug list with 60 lines per second. The Headpos2 command is send out 60 times each second and has no purpose for the timesource, it just retrieves the position of every head movement (pushes up cpu usage while debugging) It would be better to add it again: **if (Encoding.utf8.GetString(datagram).Contains("headpos2")) return;**

The "Load" command actualy loads and starts playing the file, there is currently no workaround at this point, since i just found out that the setting in the app "Autoplay file on load" only works with playing the next file in the folder on end of the current one..... You have deleted the **_timesource.Play** here, but, that would be ok when streaming files since the player will not start in sync anyway when streaming (loading takes some time and play will start directly in scriptplayer) But, when loading a local file (from phone), it will be in sync, so it would be better just to add it again. The good news about the current commands is that Samsung has confirmed to me today they will update the commands "Loading" and "Resume" in a future update. The only bad news here is that they could not give me an estimate on when it will be updated.... So i might take some time to get this fixed. When they do, i will help you with updating the interpretline code :-) Most users will use the DLNA media server option, most phones do not have much storage space.....

Getting the file from the "Url" in the command "Load", won't work when streaming from a DLNA server. This is because almost all DLNA servers, tend to send a transcoded file and therefore the filename will be completely different (random names such as 1_MTVfNmEzMWU0MzgtMzUyMzg.mp4) All files i have tested just contain the original mp4 filename in the title.

You have forgot to change: IPEndPoint source = new IPEndPoint(IPAddress.Any, **5000**); in **OnUpdData**. 5000 should be **_connectionSettings.UdpPort** like you did at the beginning of the **ClientLoop**

The Samsung VR app call the "Stop" command each time the user exits a video, so that is why it does make sense to pause, and reset the location to 0.

You did some decent coding on finding parts within the commands (like the title) and some other changes. That's the benefit of being a experienced C# coder i guess 👍 I got stuck on VB for to long, but then again, i do not code a lot. 

If you need anymore info, just ask! I could help you with a short documentation for your wiki, if you like (this weekend)

**Comment by FredTungsten** [comment]
Damn, I knew I'd make some things worse ^^
The "headpos2" and "Autoplay on load" thingies should be fixed in the next commit. Too bad they don't send the current video position with each "headpos2" too, that would make things a lot easier.

Another option would be to use VLC as DLNA server and connect to VLC instead of Samsung VR directly (just a random thought, not a fully fledged idea).

One question: Do the play/pause/seek commands work (From ScriptPlayer to Samsung VR)?

**Comment by FredTungsten** [comment]
Should be fixed in commit e225eaea4a70367fa85750b55275038d67162a2d

**Comment by RickNLX** [comment]
That's a good point about setting the position in th Headpos2 command. I might bring that up with the developpers, see if they could change that. VLC does not let you select folders, so you would have to adjust your media server every time, and select the files you want to output manually.... I am not sure what VLC does with the filenames though, i will check that out.

The commands play/seekto/pause, work ok :)

**Comment by RickNLX** [comment]
Sending the commands to GearVR, works except it throws an exception error on JObject data = JObject.Parse(message); with each command.... The commands that sciptplayer sends out to the app are not in JSON format like the recieve commands.

**Comment by RickNLX** [comment]
I did not have much time earlier, but just did some proper testing:

**"Reciever mode" Commands from SamsungVR to GearVR**
It works ok now, although i think the best mode will still be letting SamsungVR send the commands to scriptplayer (Presentation mode), so you can keep your headset on and use the gearvr controller. Also, you will have to load up the right script each time you open a video in SamsungVR  in reciever mode. Unfortunatly, turning on both reciever mode and presentation mode at the same time is not supported.

**Presentation mode Commands from SamsungVR to Scriptplayer**
I have found that the JObject data = JObject.Parse(message); still throws errors in some "headpos2"cases. It seems to break on (copy/paste from debug): 

{"cmd":"headpos2", "data":{"qw":"0.9923689","qx":"-0.007082187","qy":"-0.1195173","qz":"-0.02948747","tx":"0","ty":"0","tz":"0"}

_Newtonsoft.Json.JsonReaderException: 'Unexpected end of content while loading JObject. Path 'data', line 1, position 128.'_

I am note quite sure why actually..... Any clues? For now, my coded version still blocks the entire "headpos2" command, so i can at least use that for now 👍 

O yeah and a little but important detail when releasing: You have forgotten to change the udp port 5000 value to _connectionSettings.UdpPort in OnUpdData

**Comment by FredTungsten** [comment]
>Unexpected end of content while loading JObject. Path 'data'
That's because that's not valid JSON. It's missing a closing bracket at the end ... 

Receiver mode / Presentation mode
Oh those are exclusive, well that's ok I guess, the play/pause in ScriptPlayer are a bit unneccessary anyways.

UdpData & Connection Text
Ok, will do

**Comment by FredTungsten** [comment]
Done: 269daaed28d174c69b590ea1ad5b4d655e411af2

Added a workaround that ignores packets containing "headpos2" and fixed the port 5000 settings. I've left the "Receiver Mode" out of the description (Presentation Mode seems to be the better option) but changed "Not Connected" to "No data received", considering that UDP Broadcasts are used.

**Comment by RickNLX** [comment]
Good decision of leaving reciever mode out. No one will use it really. Presentation mode will offer users a hasle free experience. Next step for me would be to wait for Samsung's dev. team to add the nescessary extra commands.  Attached you will find the instruction you could use, when you release this version.

[svrwiki.txt](https://github.com/FredTungsten/ScriptPlayer/files/1713860/svrwiki.txt)

So far, good job man and nice collab on this one!

**Comment by FredTungsten** [comment]
I'm closing this issue since the implementation is done for now, feel free to create new issues and/or PRs for further changes.

**Comment by seandudley37774** [comment]
Just noticed that Samsung released an updated version of Samsung VR today, and in the version notes, it says, "Fixed bugs related to receiver and presentation mode."  I don't know if that includes providing the extra commands needed for syncing over DLNA or not, but hopefully it does.  Fingers crossed.
