### ISSUE TITLE
webm support

### ISSUE THREAD

**Issue by t1t7mgn6k1n** [FredTungsten/ScriptPlayer#50]
I can drag webm files onto player but it doesn't play them. If I rename them to mp4 they start to play.

**Comment by FredTungsten** [comment]
I've added "webm" to the list of supported extensions in commit e04fadb2d9fdc74aca025380403c3cbf8ba81876. If you still can't open it directly, try opening it with Windows Media Player - if you get a warning about the file (blabla untrusted source blabla), allow it to open the file and tick the "remember" (or something like that) checkbox.
