### ISSUE TITLE
Loop whole video checkbox

### ISSUE THREAD

**Issue by t1t7mgn6k1n** [FredTungsten/ScriptPlayer#52]
The loop A loop B is nice but if I want to loop the video I always have to jump to beginning, click on loop A, jump t end click on loop B.

Would be nice if you could add a third checkbox menu item to loop the current video.

**Comment by FredTungsten** [comment]
Will do, in the meantime you can add a single video to the playlist and loop the playlist.

**Comment by FredTungsten** [comment]
Included in commit e7725bcdfcc76b5a6d9471de35ee3434bd695b4c
