### ISSUE TITLE
Feature Request: Mouse control

### ISSUE THREAD

**Issue by g-coded** [FredTungsten/ScriptPlayer#60]
I've been experimenting on getting games to control the launch and found that using webcam mouse controls work close to 1:1 in real time.  This is occasionally accurate enough that even the cursor y position could set the launch position, however there is also 'drift' and the mouse can hit the screen limitations.  The speed and direction are however very synchronized.  This also works well for pov videos and might even give script writers(if mouse movement values could be recorded?) a starting script that could be refined to match.

**Comment by FredTungsten** [comment]
I've planned to add something like that to VideoSync once I've clean it up a bit and made it usable (Maybe 2018/2019, idk), but I doubt it will make it all the way to ScriptPlayer. The problem with real time controls is that you'll never know where the movement will end up which always results in rather large delay.

**Comment by g-coded** [comment]
I agree, trying to get the absolute position can go wrong in one false movement and throw everything following that point off.  Even a 'follow mouse direction' would be sufficient, this would only work with fixed camera pov videos/games anyway, and there is only so far 'face' detection can move until it has to return the other direction.
