### ISSUE TITLE
Extract script sequence

### ISSUE THREAD

**Issue by t1t7mgn6k1n** [FredTungsten/ScriptPlayer#63]
This might be a very specific feature request but is there a way to extract a specific script sequence? 
The reason is that on some videos which are +40 minutes I'm only interested into a specific scene. I can cut the video myself but not the script.

Would be nice to give start and end and retreive the script for this timespan only. Perhaps this is useful in other cases as well

**Comment by FredTungsten** [comment]
Can be done now with the menu options under "Script" ("Shift" and "Trim").
