### ISSUE TITLE
Issue Playing .avi Filetype

### ISSUE THREAD

**Issue by 369time** [FredTungsten/ScriptPlayer#65]
I'm trying to use these 3 script files @ http://realtouchscripts.com/viewtopic.php?f=55&t=6493

Two of the three videos are .avi, and simply do not play in ScriptPlayer (the one .mp4 works fine though).

The two .avi files play fine in VLC.

From what I can tell, ScriptPlayer is supposed to support .avi: [link to source](https://github.com/FredTungsten/ScriptPlayer/blob/29a5558201e608c99875631619ccce6dbddc7e9f/ScriptPlayer/ScriptPlayer.BundleHelper/MainWindow.xaml.cs#L36-37)

When I attempt to open either of the .avi`s, I get the normal notification(s) of "Loaded <name>.funscript" and "Loaded <name>.avi"

However, the player simply remains blank and nothing appears to actually load.  This is true for both the stable-1.0.5 release and the debug-1.0.5.125; there is a slight difference in that the debug player will show the script's "color meter" (the indicator at the bottom that shows the script's timeline via color), whereas the stable player doesn't load the color-bar.  But neither version appears to load the video.

Thanks for any thoughts you may have.

**Comment by FredTungsten** [comment]
Tried this?
https://github.com/FredTungsten/ScriptPlayer/wiki/Troubleshooting#the-video-doesnt-load--screen-stays-black

**Comment by 369time** [comment]
Thank you Fred!

Note to others: the "K-Lite Codec" in that link Pack solved my problem
