### ISSUE TITLE
Update NLog to latest version, instead of BETA

### ISSUE THREAD

**Issue by snakefoot** [FredTungsten/ScriptPlayer#66]
https://github.com/FredTungsten/ScriptPlayer/blob/bc4740f0b2e44e959b6cda1c8e140e4b33347133/ScriptPlayer/ScriptPlayer.Shared/packages.config#L13

NLog 5.0.0-BETA has been pulled. NLog 4.5.0+ is the new version: https://www.nuget.org/packages/NLog/

**Comment by FredTungsten** [comment]
Updated in commit 26041ab8acb1a24fa8ea9628afe6ed0a9d7146da

**Comment by snakefoot** [comment]
@FredTungsten You have updated everything but NLog. Think you need to explicitly choose NLog ver. 4.5.7

**Comment by FredTungsten** [comment]
Well, damn ^^ - now it should be fixed
