### ISSUE TITLE
Feature Request: Script Pause

### ISSUE THREAD

**Issue by dastardlii** [FredTungsten/ScriptPlayer#70]
I'd like to request a control be added, either configurable or a hard-coded keyboard command, to pause the script, but leave the video playing.  Specifically, a command to toggle the source between "None" and whatever was selected last.

Currently, you can only really do this with your mouse by using the right-side menu in the GUI, which is not ideal.

**Comment by FredTungsten** [comment]
Sure, how about the "S" and the "Stop" key?

**Comment by dastardlii** [comment]
Sounds good.  Speaking of the controls, are there any plans to make the rest of the keyboard controls re-bindable?

**Comment by FredTungsten** [comment]
Yes - the next version (whenever it will be done) will include a section in the settings dialog where you can configure keyboard shortcuts. At first I'll add basic commands like Play/Pause/Next/Fullscreen, additional commands as I see fit or by request.

**Comment by mument** [comment]
The stop script feature (while allowing the video to continue) would be great and configurable keys would be good too. I would then map the 'stop script' to the space bar so I could stop the script 'blind' while wearing a VR headset.

**Comment by FredTungsten** [comment]
Keys are already configurable in the beta, but the space key won't work. When wearing a VR headset and using an external mediaplay (e.g. Whiligig), that program usually has the focus and will receive all keyboard inputs. That would only work with media keys (the play/pause/etc. keys some keyboards have) but they are not configurable yet.

**Comment by FredTungsten** [comment]
Oh, well in that case it's no problem.
Just grab [the latest beta](https://github.com/FredTungsten/ScriptPlayer/wiki/Downloading-Beta-Builds), open the settings, go to __Input Mappings__ and configure the command __Toggle Source Video/None__ by clicking the pencil icon and pressing space. You should also remove (x) or change the command binding for __Toggle Play/Pause__.

![image](https://user-images.githubusercontent.com/28461114/51201843-7037ac00-18fd-11e9-8c95-426eb4606498.png)

**Comment by mument** [comment]
That's brilliant! I'll let you know if I encounter any 'beta' issues. Thanks for your help.
    On Tuesday, January 15, 2019, 6:45:51 PM GMT, Fred Tungsten <notifications@github.com> wrote:  
 
 
Oh, well in that case it's no problem.
Just grab the latest beta, open the settings, go to Input Mappings and configure the command Toggle Source Video/None by clicking the pencil icon and pressing space. You should also remove (x) or change the command binding for Toggle Play/Pause.
