### ISSUE TITLE
Troubleshooting on Linux

### ISSUE THREAD

**Issue by SomeoneFarAway** [FredTungsten/ScriptPlayer#71]
So i got this working with wine, on Linux. ([Screenshot](https://imgur.com/a/oxXPjJY))

But there are some limitations:
-> no direct connect via Bluetooth, so Buttplug server required
-> no local video player, so VLC is required

A breaking problem is, that i can set the source to Slow/Medium/Fast/Random/ZigZag and it works flawless, but when i try to load a funscript it's not doing anything.

i suspect that it somehow tries to use the local player even in blindmode, because i get a lot of directx errors while playing a script.

Wine configuration:
wine-3.15 (Staging) x64
winetricks dotnet462 corefonts

What i tried:
i tried to install K-Lite and Directx9 with no improvements

I will try to get the funscript working first, since it's useable then. So if anyone has an idea, i would appreciate the input :)

**Comment by FredTungsten** [comment]
The funscript seems to load fine because you can see the heat-map at the bottom. The DirectX errors could come from WPF itself, since it's DirectX based (as opposed to GDI+ in WinForms). Unfortunately I have no experience with Wine so I wouldn't even know where to look.

**Comment by Enissay** [comment]
It is super sad this is not working on Linux :'(
