### ISSUE TITLE
Launch unresponsive after 1st playthrough video ends using Repeat video feature 

### ISSUE THREAD

**Issue by realcumber** [FredTungsten/ScriptPlayer#72]
I have been trying to make repeat video/script work (tried both repeat all, and repeat once buttons) but once the video plays through once, the launch stops moving, and the video and script repeats but the launch doesn't respond or move anymore at all.
I have to close the app and reopen and reconnect the launch from the menu again to get the launch responsive again

**Comment by FredTungsten** [comment]
Weird. I know this was an issue in older Versions, but the latest (which isn't exactly new either) shouldn't have that problem.

**Comment by realcumber** [comment]
Actually just tested since you commented that it sholuldn't be a problem.  I had Autofill gaps with movements setting on, turning that off allowed me to play the videos on a loop without issue!
