### ISSUE TITLE
ScriptPlayer not connecting to Launch

### ISSUE THREAD

**Issue by adamhia** [FredTungsten/ScriptPlayer#73]
I'm on Win10 - Version	10.0.17134 Build 17134
FeelConnect - 2.1.7

ScriptPlayer isn't recognizing the Launch...any ideas?

**Comment by FredTungsten** [comment]
Might be your BT Dongle, have you checked the [Troubleshooting Guide](https://github.com/FredTungsten/ScriptPlayer/wiki/Troubleshooting)?

**Comment by FredTungsten** [comment]
http://realtouchscripts.com/viewtopic.php?f=58&t=6840#p16925
