### ISSUE TITLE
"Cum" function with key shortcut

### ISSUE THREAD

**Issue by asphalter** [FredTungsten/ScriptPlayer#75]
Hi FredTungsten,

I'm suggesting you to implement a function to let the toy play a simple slow sweep or a brief script (preloaded to avoid delays at start) to be activated when, watching a video, the watcher simply "cum". Now the watcher is forced to stop the video (and the toy), and maybe manually activate a slow sweep from the right tool menu.

Could you please implement this new request?

Thank you
Best regards,
Asphalter

**Comment by FredTungsten** [comment]
Hi Asphalter,

I'm currently working on adding configurable keyboard shortcuts - together with the already existing settings for a "Pattern" beat source, I think you might be able to do something like that. I'll let you know when it's available in the [beta](https://github.com/FredTungsten/ScriptPlayer/wiki/Downloading-Beta-Builds).

BR, FT

**Comment by asphalter** [comment]
Perfect, thanks FredTungsten, will immediately try and give feedback once available.

**Comment by FredTungsten** [comment]
[The latest beta](https://ci.appveyor.com/project/FredTungsten/scriptplayer/build/job/1y2x70b6nsy1bswl/artifacts) supports more input bindings, here is how you could set them up:

1. In the "Source" section of the settings panel on the right, select a pattern and pattern speed (e.g. Up/Down 140 ms)
2. Open the Settings dialog via the top menu and select "Input Mappings"
3. Double-Click "Toggle Command Source" or click the pencil icon to assign a Keyboard Shortcut (e.g. "C" for Cum)
4. Press "C" to toggle between the current video script and the preset pattern

Let me know what you think - BR, FT

**Comment by asphalter** [comment]
Thanks FredTungsten, wil:-)l give a try and let you know

**Comment by asphalter** [comment]
Seems to work flawlessly, thanks for your promptly help!

**Comment by FredTungsten** [comment]
No problem. No idea when the next release version will be ready but this feature will of course be included in this or a similar way.
