### ISSUE TITLE
Launch out of sync with Samsung VR (Fast Forwarding)

### ISSUE THREAD

**Issue by whoibe** [FredTungsten/ScriptPlayer#78]
When I load a file and play it from the start, the launch works fine but once I start fast forwarding to a another section.  It seems like the launch gets all out of whack.  It doesn't follow the scripts that's being played.  I tried reloading the file and pausing but that doesn't seem to fix the issue.

I am using samsung vr in presentation mode and when I fast forward , the heat map and everything looks good on the scriptplayer but it's just the launch that is out of sync.  Not sure if this is a player issue or the dongle that's not keeping up.  Please help.  Thx

Using Gear VR
Os: Win 10
Bluetooth 4.0 CSR dongle (usb2.0 port)

**Comment by FredTungsten** [comment]
Unfortunately I can't help with that since I don't own a Samsung. This feature was added by RickNLX in issue #40 - maybe he can help.

**Comment by RickNLX** [comment]
Unfortunately, samsung still has not added the right commands to its presentation mode... Only way to bypass out of sync, is to press pause first, then seek another position in the video and wait while buffering is done (when streaming) and then press play again. That way, the right position is send to scriptplayer.

**Comment by whoibe** [comment]
Sorry I am not computer savvy at all.  Rick the file that you made.  From my understanding I just copy this file ? "SamsungVRTimeSource.cs"  Where do I copy that to?  Do I copy it into the scriptplayer folder? Or do I copy it into a folder on the phone?  Please assist as I am lost lol. Thanks

**Comment by RickNLX** [comment]
You do not need that file, thats for developpers only. You will just need to install scriptplayer and follow the instructions in the wiki

**Comment by whoibe** [comment]
Thanks for the quick reply Rick.  Are you talking about the wiki that says use the device in presentation mode?  I did that and it works, but ones I start skipping around the device stops following and goes all out of whack.
