### ISSUE TITLE
Check if Launch is paired

### ISSUE THREAD

**Issue by FredTungsten** [FredTungsten/ScriptPlayer#79]
Launch is a BLE device and must no be paired to work

**Comment by raser1** [comment]
Hi Liquid, I was just looking into this and found a way to detect it :) 

Here is the code:

```
static public bool IsLaunchPaired()
{
	var scope = new ManagementScope(@"\\" + Environment.MachineName + @"\root\CIMV2");
	var sq = new SelectQuery("SELECT Name FROM Win32_PnPEntity WHERE Name='Launch'");
	var searcher = new ManagementObjectSearcher(scope, sq);
	var moc = searcher.Get();

	foreach (ManagementObject mo in moc)
	{
		object propName = mo.Properties["Name"].Value;			
		Debug.WriteLine("Launch is paired!");
		return true;
	}
	
	return false;
}
```

I've also found a way to disable it automatically, but it requires Admin privileges.

**Comment by FredTungsten** [comment]
Hey, awesome!
Thanks for that - I'll put that in over the weekend.

**Comment by FredTungsten** [comment]
> 
> 
> BTW, I _think_ there might be a way to access paired devices also?

That would be convinient. That might solve the issue some people have with their BT dongles where the Launch disconnects after a couple of seconds of inactivity. (If that's still happening - I guess most og them just got a new dongle)

**Comment by FredTungsten** [comment]
Works like a charm

**Comment by qdot** [comment]
> > BTW, I _think_ there might be a way to access paired devices also?
> 
> That would be convinient. That might solve the issue some people have with their BT dongles where the Launch disconnects after a couple of seconds of inactivity. (If that's still happening - I guess most og them just got a new dongle)

In my experience, this usually has to do with power saving settings, in relation to Insignia dongles especially. You can turn that off. See the "Disable Bluetooth Power Management" portion of https://www.howtogeek.com/189856/ask-htg-how-can-i-keep-my-bluetooth-mouse-connected/.

**Comment by FredTungsten** [comment]
Added that to the troubleshooting section of the wiki
