### ISSUE TITLE
Fuzzy matching for script names

### ISSUE THREAD

**Issue by FredTungsten** [FredTungsten/ScriptPlayer#80]
Plex seems to add " (yyyy)" to the name of files, maybe a regex-based pattern matching can cover that edge-case.

http://realtouchscripts.com/viewtopic.php?f=59&t=6160&start=30#p19431

**Comment by FredTungsten** [comment]
``^(?<Title>.+)\s?\(\d{4}\)$`` replace with ``${Title}`` would be an option

**Comment by qwksilver** [comment]
Not to reopen this, but it's appropriate here:
Can you document, or point me to the document, that shows how this works in script player specifically.
my goal would be to use this [^a-zA-Z] to strip the titles of non alpha characters, and probably a second thing to limit the compare to all but the last 8 character or so.

sample:
bob_and_marie_together 1080p.mkv 
bob and marie together.funscript
after the regex getting bobandmarietog vs bobandmarietog  match!

even eventually adding expressions to drop whole sections bound by () [] {}

ultimately for this to work, i need to know:
does this work on both the script file and the video file. and then compare the two to find matches. 
or does it only work on the video name.

**Comment by FredTungsten** [comment]
It only works on video file names transmitted by external players and was intended for use-cases where the player modifies the video file name.

If the title/file name is a match to the regex pattern, the defined replacement will be used instead.

e.g. 

http://regexstorm.net/tester?p=%5e%28%3f%3cTitle%3e.%2b%29%5cs%3f%5c%28%5cd%7b4%7d%5c%29%24&i=Test+Title+%282010%29&r=%24%7bTitle%7d

```
Regex regex = new Regex(FuzzyMatchingPattern);

if (regex.IsMatch(videoFileName))
{
    videoFileName = regex.Replace(videoFileName, FuzzyMatchingReplacement);
}
```
