### ISSUE TITLE
Range Extender

### ISSUE THREAD

**Issue by FredTungsten** [FredTungsten/ScriptPlayer#85]
"Stretch" Script positions by X percent between high and low peaks

**Comment by gagax1234** [comment]
Oh wow I like this alot.
I can see alot of scripts greatly benefiting from this.

**Comment by FredTungsten** [comment]
Yep, a lot of scripts sometimes just slightly *wobble* around the same position without causing any real movement. With this, any small twitch can be turned into a full stroke (already part of the beta, changes are visible in the position bar in real-time)

**Comment by gagax1234** [comment]
> Yep, a lot of scripts sometimes just slightly _wobble_ around the same position without causing any real movement. With this, any small twitch can be turned into a full stroke (already part of the beta, changes are visible in the position bar in real-time)

exactly.
you could also add the ability to save this setting directly in the funscript file.
that way you wouldn't have to fiddle with that setting every time you load a new script.

**Comment by FredTungsten** [comment]
I might add an option so save the script as it is sooner or later, besides the range extender that could also include command delays and other options. #92

**Comment by gagax1234** [comment]
Another thing could be multiple "modes" for example:

- **threshold**: where range is only extended if it's below a certain threshold
- **no idea what to call this** : the larger the range the less effective is the range extender at further extending it

don't think of this as feature requests I'm just throwing around ideas

**Comment by FredTungsten** [comment]
Right it's moving the most top and bottom positions by a fixed value and scaling all values in between. The problem is, that the "peaks" will have positions before and after them and no matter how I move the peaks it should fit the commands on both sides - haven't had any good ideas how to handle that so far. (e.g. 75, 80, **90**, 50, **0**, **50**, 45, 40, **35**, **100** --> ?)

Addition is the operation that works in any case.

**threshold**: If one range of values surpasses the threshold and the other one doesn't ... what do I do.
**no idea what to call this** --> uhm... "non-linear range extension"? (maybe on a log or pow scale) Same problem - would have to work on both sides.

**Comment by gagax1234** [comment]
I see now it's not as easy as I initially thought. I'll play some more around with this.
