### ISSUE TITLE
"Show Script Positions" rendering after it was disabled 

### ISSUE THREAD

**Issue by gagax1234** [FredTungsten/ScriptPlayer#91]
I found this minor issue while using the Performance Profiler from Visual Studio on ScriptPlayer and found that rendering the "TimeLineHeader" is actually pretty expensive 90% of it being the "DrawText" calls but that's not the issue.

The issue is that if you enable "Show Script Positions" once and then disable it again the timeline will still be rendered in the background even though it's not visible for rest of the lifetime of the program.

The "TimeLineHeader" correctly doesn't render in the background if it has never been enabled during the runtime of the program.

I'd fix it myself but I couldn't figure out how it works. WPF and those DependencyProperties are still a mystery to me. 😅

**Comment by FredTungsten** [comment]
I meant to fix that but it never really bothered me enough to do something about it. I've just committed a quick fix that disables rendering when the control isn't visible, but a proper fix would require a considerable redesign of the control,

**Comment by gagax1234** [comment]
nice this definitely better.
