### ISSUE TITLE
Whirligig only working for localhost

### ISSUE THREAD

**Issue by lynceus666** [FredTungsten/ScriptPlayer#99]
After playing around with the Whirligig-implementation in ScriptPlayer I found out that I can't bring ScriptPlayer to connect to Whirligig on a remote PC. Whatever I do, ScriptPlayer always tries to connect to Whirligig on localhost, obviously ignoring the settings in the "Players" menu.

I can remote connect (local network) to VLC, MPC-HC and Samsung VR, but it doesn't seem to work for Whirligig.
Is it just me or is this a bug (either in Whirligig or in ScriptPlayer)?

**Comment by FredTungsten** [comment]
Must be an issue with Whirligig - not necessarily a bug, it might be by design since it's not password-protected.

**Comment by raser1** [comment]
I don't have anything to test this myself, but you can change the IP address in the settings file: `%APPDATA%\Whirligig\production\playersettings.ini`

By default it's localhost only: `timecodeserver=127.0.0.1`, maybe it will work if you change this to your local IP. You might have to open port 2000 in the firewall too.

**Comment by lynceus666** [comment]
Thanks for the info, raser1.
Didn't know there was a settings-file for Whirligig, good idea. 
Just tried to change the IP to my local IP, but unfortunately I still can't connect.
Port 2000 is open in my local network, I could connect MPC with ScriptPlayer successfully over port 2000. But unfortunately it doesn't work with Whirligig.
